//! What a `.tm` file records ABOUT its machine, as opposed to the machine itself.
//!
//! A Turing machine is a transition function plus an initial configuration. The text form serialized
//! only the first half: `print_tm` emits δ and q₀ and nothing about how the machine STARTS, so a
//! printed machine round-tripped faithfully as a machine and still could not be run or read back from
//! the file alone. `TmHeader` is the second half — the literal initial tapes, so any TM simulator can
//! run the file with no knowledge of this project's encodings, plus the `encoding`/`width`/`slots`/
//! `result` recipe needed to interpret the answer.
//!
//! **The header is OPTIONAL and adds no capability to the machine — it removes an INPUT requirement.**
//! `simulate(&m, &init, caps)` needs the caller to supply `init`; with a header, `init` can come from
//! the file instead. Nothing about δ, the start state, or execution changes, which is why a
//! header-less file stays exactly as runnable as it was.
//!
//! **Returned alongside a `Machine`, never stored on one.** `lower_tm.rs` states the rule twice:
//! `Machine` derives `PartialEq` and the round-trip asserts `parse_tm(print_tm(m)) == m`, which a
//! side-table field would break for a reason unrelated to what the machine computes.
//!
//! The one thing a header CANNOT do, stated here rather than discovered later: a foreign tool can RUN
//! a `.tm` file but cannot INTERPRET its result. Running is universal; interpreting needs the
//! encoding's semantics, and a name cannot convey them.

use crate::Span;
use crate::tm::build::{BOX, HEAP, MAX_FIELD_WIDTH, REG, STACK, WORK};
use crate::tm::encoding::{Binary, Encoding, Unary};
use crate::tm::lower_tm::MAX_SLOTS;
use crate::tm::machine::Symbol;
use crate::ty::Ty;
use crate::ty::parse_ty;

/// The `.tm` header format version this build writes and accepts.
///
/// An ABSENT `version` directive means 1, so every file written before this directive existed stays
/// valid. An unknown version is a hard parse ERROR rather than a warning: a future version could
/// change what `width` or `slots` MEAN, and decoding a v2 file under v1 rules would produce a
/// confidently wrong value — the exact failure the header exists to prevent.
///
/// NOT a member of the four-directive header set (`encoding`/`width`/`slots`/`result`), so the four
/// optionality properties are unaffected and a header-less file is still header-less.
pub const HEADER_VERSION: u32 = 1;

/// Declares `EncodingKind` and every list that must know about it, from ONE invocation.
///
/// THE POINT: `ALL`, `at`, `name` and `parse` are generated from the same rows, so they cannot drift.
/// Adding an encoding is one line here; a hand-written `ALL` beside a hand-written enum could not give
/// that guarantee, because nothing in stable Rust compares a written-out list against the variant set —
/// a developer can satisfy every exhaustive match and still leave the list short.
///
/// COST, stated because it is real: the enum is macro-generated, so it is less greppable and produces
/// weaker rustdoc than a plain `enum`. The invocation below is the definition — read it as one.
macro_rules! encoding_kinds {
    ($( $(#[$meta:meta])* $variant:ident => $name:literal => $ty:ty ),* $(,)?) => {
        /// Which `Encoding` a file names.
        ///
        /// Generated by `encoding_kinds!` together with `ALL`/`at`/`name`/`parse` — see that macro for
        /// why. **Adding an encoding means adding one row to the invocation below, nothing else.**
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum EncodingKind {
            $( $(#[$meta])* $variant ),*
        }

        impl EncodingKind {
            /// Every kind, in declaration order. Generated from the same rows as the variants, so it
            /// cannot omit one. Iterate this rather than writing a list out: a hand-written list is a
            /// place a future encoding gets silently left out of.
            pub const ALL: &'static [EncodingKind] = &[ $( EncodingKind::$variant ),* ];

            /// This kind instantiated at `width` cells. EVERY kind in this registry must be BOUNDED
            /// (`field_width()` is always `Some`), which is why the producer in `tm.rs` needs no
            /// unbounded early-return branch the way `run_tm_fitted` does — an unbounded encoding has
            /// no name in this enum to write in a file. This doc text is emitted regardless of row
            /// count, so it says "every" rather than naming the current two — a row added here without
            /// a bounded `Encoding` behind it would go stale on exactly this line.
            /// `encoding_kind_instantiates_the_named_encoding_at_the_given_width` (below) pins
            /// boundedness for every kind in `ALL`, not just the two named at the time it was written.
            pub fn at(self, width: usize) -> Box<dyn Encoding> {
                match self {
                    $( EncodingKind::$variant => Box::new(<$ty>::at(width)) ),*
                }
            }

            /// The name written in an `encoding` directive. Lowercase, matching the rest of the text
            /// form's keywords (`tapes`, `start`, `state`, `accept`).
            pub fn name(self) -> &'static str {
                match self {
                    $( EncodingKind::$variant => $name ),*
                }
            }

            /// The inverse of `name`. `None` for an unrecognized name, which the parser reports as a
            /// diagnostic rather than defaulting — a file naming an encoding this build does not have
            /// is unreadable, and guessing would decode its tape as something else entirely.
            pub fn parse(s: &str) -> Option<EncodingKind> {
                match s {
                    $( $name => Some(EncodingKind::$variant), )*
                    _ => None,
                }
            }
        }
    };
}

// THE REGISTRATION POINT. One row per encoding: variant, its name in a `.tm` file, its `Encoding` type.
// Adding a row updates `EncodingKind`, `ALL`, `at`, `name` and `parse` together.
encoding_kinds! {
    /// Unary: value `n` is `n` filled cells, so a `w`-cell field holds `0..=w`.
    Unary => "unary" => Unary,
    /// Binary: a `w`-cell field is base-2, holding `0..2^w`.
    Binary => "binary" => Binary,
}

/// This compiler's name for tape `i`, used only for the trailing comment on a `tape` line.
///
/// Tapes are addressed by INDEX in the format (spec D3): names are this compiler's convention, not a
/// property of a Turing machine, and a generic simulator knows only indices. `None` for an index
/// outside this layout, which a file with a larger `tapes N` may legitimately have.
pub(crate) fn tape_name(i: usize) -> Option<&'static str> {
    match i {
        REG => Some("reg"),
        WORK => Some("work"),
        STACK => Some("stack"),
        HEAP => Some("heap"),
        BOX => Some("box"),
        _ => None,
    }
}

/// The header of a `.tm` file. See the module doc for why this is not a field on `Machine`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TmHeader {
    /// Which encoding reads this machine's tapes.
    pub encoding: EncodingKind,
    /// Field width in CELLS. What a field of that many cells can HOLD is the encoding's business
    /// (`v < width` for unary, `v < 2^width` for binary).
    pub width: usize,
    /// REG bank field count.
    pub slots: u32,
    /// The type of the program's RESULT VALUE — NOT "the final tape" (tape `TAPES - 1`, the BOX bank,
    /// is typically unused). The value is read from REG field 0 (`Reg::Rr`) and, for a `List<T>`,
    /// followed as a pointer into the HEAP tape (see `build::AT` for the cons-cell layout — it covers
    /// BOTH encodings, which matters here because a header may say `encoding binary`, whose head/tail
    /// words are fixed-width digit strings rather than the variable-length mark runs `encoding::unary`
    /// describes; `decode::decode_tape_ty` is the reader). Only `Nat`/`Bool`/`Unit`/`List<T>` are
    /// admissible.
    pub result: Ty,
    /// Literal initial contents by tape INDEX, ascending, with EMPTY TAPES OMITTED. Private because
    /// `new` maintains that normal form and the round-trip depends on it — see `new`.
    tapes: Vec<(usize, Vec<Symbol>)>,
}

impl TmHeader {
    /// Build a header, normalizing `tapes` into the form the text output can represent exactly:
    /// empty tapes dropped, indices ascending, and duplicate indices collapsed to one entry — but
    /// NOT always "the first" of the input. Empties are dropped BEFORE the duplicate collapse runs,
    /// so an empty entry never wins a duplicate index merely by coming first: `[(0, []), (0, ['#'])]`
    /// keeps the SECOND entry, because the first is already gone by the time dedup sees the list.
    /// Only among the entries that survive the empty drop does input order decide the winner.
    ///
    /// The normalization is not cosmetic. An omitted `tape` line MEANS "this tape starts empty"
    /// (which is how HEAP, STACK and BOX always start), so an explicitly-stored empty entry prints
    /// nothing and parses back to no entry — and `parse_tm_full(print_tm_with(m, h))` would return a
    /// header unequal to `h`, breaking optionality property 2 over a difference that carries no
    /// information. Normalizing at construction makes the round-trip exact instead of approximate.
    ///
    /// **PRECONDITION for the round-trip, unenforced here.** This constructor accepts any `width` and
    /// `slots`, but `parse_tm_full` caps them at `MAX_FIELD_WIDTH` and `MAX_SLOTS` (totality guards on
    /// untrusted input). So a header built with `width: 0`, `width > MAX_FIELD_WIDTH` or
    /// `slots > MAX_SLOTS` will PRINT and then fail to parse back — optionality property 2 holds for
    /// headers within those caps, not for every value this constructor admits. `run_tm_described`, the
    /// only producer in the tree, cannot exceed them: its width comes from the auto-fit search, which
    /// clamps at `MAX_FIELD_WIDTH`, and its slot count from `lower_and_size`, which refuses above
    /// `MAX_SLOTS` before a machine is ever built. The caps are not re-checked here because doing so
    /// would make a pure normalizer fallible for a case its only caller cannot reach — but a hand-built
    /// header is outside the guarantee, and that is stated here rather than discovered at parse time.
    pub fn new(
        encoding: EncodingKind,
        width: usize,
        slots: u32,
        result: Ty,
        tapes: Vec<(usize, Vec<Symbol>)>,
    ) -> TmHeader {
        let mut tapes: Vec<(usize, Vec<Symbol>)> = tapes.into_iter().filter(|(_, c)| !c.is_empty()).collect();
        tapes.sort_by_key(|(i, _)| *i);
        tapes.dedup_by_key(|(i, _)| *i); // duplicates are sorted adjacent, so this keeps the first
        TmHeader { encoding, width, slots, result, tapes }
    }

    /// The literal initial tapes, by index, ascending, empties omitted.
    pub fn tapes(&self) -> &[(usize, Vec<Symbol>)] {
        &self.tapes
    }

    /// The `Encoding` instance this header names, at its width. This is the half a foreign reader
    /// cannot reproduce — it needs the implementations, which the header names but cannot inline.
    pub fn encoding(&self) -> Box<dyn Encoding> {
        self.encoding.at(self.width)
    }

    /// The initial tape vector to hand `simulate`, from the literal `tape` lines. `n_tapes` comes
    /// from the file's `tapes N`. Entries outside `0..n_tapes` are dropped rather than panicked on, so
    /// a header and a tape count that disagree still yield a runnable configuration.
    ///
    /// **Not total in `n_tapes` itself.** The allocation below is `n_tapes` `Vec`s, so this is bounded
    /// only because the one caller that parses `n_tapes` from a file (`syntax::parse_tm_full`) caps it
    /// at `MAX_TAPES` before it ever reaches here — see that cap's doc for why an unbounded `tapes N`
    /// is a hazard. A caller that hands this an unvalidated `n_tapes` is outside that guarantee.
    pub fn init(&self, n_tapes: usize) -> Vec<Vec<Symbol>> {
        let mut init = vec![Vec::new(); n_tapes];
        for (i, cells) in &self.tapes {
            if let Some(slot) = init.get_mut(*i) {
                *slot = cells.clone();
            }
        }
        init
    }
}

use crate::ty::show;
use std::fmt::Write as _;

/// Render `h`'s directives, one per line, ending in a newline. Emitted between `start` and the states
/// by `syntax::print_tm_with`.
///
/// The order — `version`, `encoding`, `width`, `slots`, `result`, then `tape` lines ascending — is
/// FIXED, even though the parser accepts any order. A printer has to choose one, and a fixed choice is
/// what makes re-printing a re-parse idempotent. `version` leads: it is not one of the four directives
/// `TmHeader` carries (there is no field for it — see `HEADER_VERSION`'s doc), but a reader needs to
/// know which rules govern the rest of the block before it makes sense of them.
///
/// KNOWN LIMIT: a tape cell equal to `;` would open a comment and not round-trip. No `Encoding` in
/// this tree writes one — the tape alphabet is `_ # 1 0 @` — and `Machine::validate()` already
/// reserves `;`. A hand-built machine using `;` as a data symbol is outside the representable subset
/// the text form is specified for, the same as one whose state name contains a space.
pub(crate) fn print_header(h: &TmHeader) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "version {HEADER_VERSION}");
    let _ = writeln!(out, "encoding {}", h.encoding.name());
    let _ = writeln!(out, "width {}", h.width);
    let _ = writeln!(out, "slots {}", h.slots);
    let _ = writeln!(out, "result {}", show(&h.result));
    for (i, cells) in &h.tapes {
        let packed: String = cells.iter().collect();
        match tape_name(*i) {
            Some(name) => {
                let _ = writeln!(out, "tape {i} {packed}  ; {name}");
            }
            None => {
                let _ = writeln!(out, "tape {i} {packed}");
            }
        }
    }
    out
}

/// Unpack a `tape` line's cell run: strip a trailing `;` comment, trim, and take one `Symbol` per
/// char. The inverse of `print_header`'s packing (D4).
pub(crate) fn parse_cells(s: &str) -> Vec<Symbol> {
    s.split(';').next().unwrap_or("").trim().chars().collect()
}

/// The header directives seen so far, accumulated across the parse loop so they can arrive in any
/// order. `finish` decides whether they amount to a header, a diagnostic, or nothing at all.
#[derive(Default)]
pub(crate) struct HeaderParts {
    encoding: Option<EncodingKind>,
    width: Option<usize>,
    slots: Option<u32>,
    result: Option<Ty>,
    /// The parsed, VALIDATED version — `Some` only once a `version` directive has been seen naming
    /// exactly `HEADER_VERSION`. Not surfaced on `TmHeader` (see `HEADER_VERSION`'s doc: version is a
    /// property of the FORMAT, validated here and re-emitted as a constant, not a property of any one
    /// machine's header). Its ONLY job is detecting a duplicate directive — `finish` never reads it,
    /// consulting `saw_version` below instead, because a `version` line that FAILED to validate still
    /// means the file was trying to carry a header.
    version: Option<u32>,
    /// Each entry carries the `Span` of the `tape` line it came from, so a diagnostic about ONE
    /// specific entry (the out-of-range check in `finish`) can point at the line that caused it
    /// instead of the whole file. The span is parse-time-only: `finish` strips it before handing the
    /// tapes to `TmHeader::new`, which never carries one (see that type's doc).
    tapes: Vec<(usize, Vec<Symbol>, Span)>,
    /// Whether any `tape` line was seen. Tracked separately from `tapes` because a `tape` line that
    /// FAILED to parse still means the file was trying to carry a header, and `finish` must not then
    /// report "no header".
    saw_tape: bool,
    /// Whether any `version` line was seen, mirroring `saw_tape` exactly and for the same reason: a
    /// `version` directive that failed to parse (or named an unknown version — caught earlier, in
    /// `directive`, since that error must fire regardless of what else is in the file) still means the
    /// file was trying to say something, and a LONE, valid `version` with none of the four directives
    /// must not silently read as "no header" either — that would turn a typo into invisible data loss,
    /// same as a stray `tape` line.
    saw_version: bool,
}

impl HeaderParts {
    /// Offer one non-comment line's `key` and remainder, plus that line's `span` (needed only for a
    /// `tape` line — see the field doc on `tapes`). Returns `None` if `key` is not a header directive
    /// (the caller keeps looking), `Some(Ok(()))` if it was consumed, `Some(Err(msg))` if it was a
    /// header directive that did not parse.
    ///
    /// A DUPLICATE directive is an error rather than last-wins. The rule is that the file STATES A
    /// THING ONCE — not that the values disagree: two *agreeing* `width 4` lines are refused too.
    /// Disagreeing ones are the motivating case (there is no defensible winner, and picking one
    /// silently would decode the tape against a recipe the file does not unambiguously state), but
    /// admitting agreeing duplicates would mean comparing values to decide whether a file is
    /// well-formed, which is a strictly worse rule to state and to test.
    pub(crate) fn directive(&mut self, key: &str, rest: &str, span: Span) -> Option<Result<(), String>> {
        let val = rest.split(';').next().unwrap_or("").trim();
        match key {
            // Unlike the four directives below, an unrecognized version is not "incomplete" — it is
            // refused outright, here, at the earliest point it can be: a v2 file parsed under v1 rules
            // would not fail to parse, it would parse to a CONFIDENTLY WRONG value, because a future
            // version could redefine what `width` or `slots` mean. A duplicate is an error for the same
            // reason as the other four, and on the same rule: the file states a thing once, so two
            // AGREEING `version 1` lines are refused as well.
            "version" => {
                self.saw_version = true;
                Some(match (self.version, val.parse::<u32>()) {
                    (Some(_), _) => Err("duplicate `version` directive".into()),
                    (None, Ok(v)) if v == HEADER_VERSION => {
                        self.version = Some(v);
                        Ok(())
                    }
                    (None, Ok(v)) => Err(format!(
                        "unsupported header version `{v}` (this build reads version {HEADER_VERSION} only)"
                    )),
                    (None, Err(_)) => Err(format!("expected `version {HEADER_VERSION}`, found `{val}`")),
                })
            }
            "encoding" => Some(match (self.encoding, EncodingKind::parse(val)) {
                (Some(_), _) => Err("duplicate `encoding` directive".into()),
                (None, Some(k)) => {
                    self.encoding = Some(k);
                    Ok(())
                }
                (None, None) => Err(format!("unknown `encoding` name `{val}` (expected `unary` or `binary`)")),
            }),
            // Capped at the auto-fit search's OWN ceiling: `run_tm_fitted` doubles from
            // `MIN_FIELD_WIDTH` and clamps at `MAX_FIELD_WIDTH`, so a file naming a wider field
            // describes a bank this build could not have produced and whose recipe it cannot evaluate.
            // (NOT, despite the sibling arm below, a ceiling `lower_and_size` enforces — that function
            // checks `MAX_SLOTS`, `frame_bank_unrepresentable` and `mul_count_unrepresentable`, and
            // nothing about field width.) With `slots`, this bounds `init_reg`'s
            // `slots * (width + 1)` allocation. A TOTALITY guard on untrusted input, not a language limit.
            "width" => Some(match (self.width, val.parse::<usize>()) {
                (Some(_), _) => Err("duplicate `width` directive".into()),
                (None, Ok(n)) if (1..=MAX_FIELD_WIDTH).contains(&n) => {
                    self.width = Some(n);
                    Ok(())
                }
                (None, _) => Err(format!("expected `width <1..={MAX_FIELD_WIDTH}>`, found `{val}`")),
            }),
            // Capped at the same ceiling `lower_and_size` enforces for in-memory programs, so the file
            // path and the in-memory path cannot disagree about one named limit. With `width`, this
            // bounds `init_reg`'s `slots * (width + 1)` allocation. A TOTALITY guard on untrusted
            // input, not a language limit.
            "slots" => Some(match (self.slots, val.parse::<u32>()) {
                (Some(_), _) => Err("duplicate `slots` directive".into()),
                (None, Ok(n)) if n <= MAX_SLOTS => {
                    self.slots = Some(n);
                    Ok(())
                }
                (None, _) => Err(format!("expected `slots <0..={MAX_SLOTS}>`, found `{val}`")),
            }),
            "result" => Some(match (&self.result, parse_ty(val)) {
                (Some(_), _) => Err("duplicate `result` directive".into()),
                (None, Some(t)) => {
                    self.result = Some(t);
                    Ok(())
                }
                // D5: `Fun`/`Var` are well-formed types that are not first-class tape values, so a
                // file naming one is rejected where it is WRITTEN rather than decoding to a silent
                // `None` where it is read.
                (None, None) => {
                    Err(format!("`result` must be a value type (Nat | Bool | Unit | List<T>), found `{val}`"))
                }
            }),
            "tape" => {
                self.saw_tape = true;
                let Some((idx, cells)) = val.split_once(' ') else {
                    return Some(Err(format!("expected `tape <index> <cells>`, found `tape {val}`")));
                };
                Some(match idx.trim().parse::<usize>() {
                    Err(_) => Err(format!("expected `tape <index> <cells>`, found index `{idx}`")),
                    Ok(i) if self.tapes.iter().any(|(j, _, _)| *j == i) => {
                        Err(format!("duplicate `tape {i}` directive"))
                    }
                    Ok(i) => {
                        self.tapes.push((i, parse_cells(cells), span));
                        Ok(())
                    }
                })
            }
            _ => None,
        }
    }

    /// Decide what the accumulated directives amount to, given the file's declared `n_tapes`.
    ///
    /// Each diagnostic carries an `Option<Span>`: `Some` when it is about one specific line (the
    /// out-of-range check below, which has a real offending `tape` line in scope), `None` when it
    /// isn't (there is no single line to blame for a directive that never appeared at all). The
    /// caller stamps `None` to a `Span { start: 0, end: 0 }` placeholder.
    ///
    /// - **Zero of the four present** (and no `tape` or `version` line) -> `(None, [])`: the file has
    ///   no header, which is not an error. This is optionality property 4, and it is what every file
    ///   written before this slice looks like.
    /// - **All four present** -> a validated header. (`version`, valid or absent, has already been
    ///   settled in `directive` — an unrecognized version errors there, immediately, rather than
    ///   waiting for `finish`.)
    /// - **One to three present** -> `(None, [(msg, None)])` naming the missing ones. Not a silent
    ///   `None`, because discarding a half-written header would turn a typo into "this file has no
    ///   header". Spanless: there is no single offending line for an ABSENT directive.
    /// - **`tape` and/or `version` lines but none of the four** -> an error for the same reason: that
    ///   data would otherwise vanish without a word. Also spanless, for the same reason. `version` is
    ///   folded in here rather than getting its own case because a LONE `version` has exactly the same
    ///   shape as a lone `tape`: a directive with no header for it to belong to.
    pub(crate) fn finish(self, n_tapes: usize) -> (Option<TmHeader>, Vec<(String, Option<Span>)>) {
        let missing: Vec<&str> = [
            ("encoding", self.encoding.is_none()),
            ("width", self.width.is_none()),
            ("slots", self.slots.is_none()),
            ("result", self.result.is_none()),
        ]
        .into_iter()
        .filter_map(|(name, absent)| absent.then_some(name))
        .collect();

        if missing.len() == 4 {
            return if self.saw_tape || self.saw_version {
                (
                    None,
                    vec![(
                        "`tape`/`version` directives without a header (needs `encoding`, `width`, `slots`, \
                         `result`)"
                            .into(),
                        None,
                    )],
                )
            } else {
                (None, Vec::new()) // no header, no diagnostic
            };
        }
        if !missing.is_empty() {
            return (None, vec![(format!("incomplete header: missing {}", missing.join(", ")), None)]);
        }

        // The range check lives HERE, not in `directive`, because directives are order-independent:
        // a `tape 7` line may precede the `tapes 5` that makes it out of range. Unlike the diagnostics
        // above, THIS one is about one specific line, whose span was in scope when `directive` saw
        // it — carry it, rather than throwing it away.
        let mut errs = Vec::new();
        for (i, _, span) in &self.tapes {
            if *i >= n_tapes {
                errs.push((format!("`tape {i}` is out of range for `tapes {n_tapes}`"), Some(*span)));
            }
        }
        if !errs.is_empty() {
            return (None, errs);
        }
        let (encoding, width) = (self.encoding.unwrap(), self.width.unwrap());
        let (slots, result) = (self.slots.unwrap(), self.result.unwrap());
        let tapes: Vec<(usize, Vec<Symbol>)> = self.tapes.into_iter().map(|(i, cells, _)| (i, cells)).collect();
        (Some(TmHeader::new(encoding, width, slots, result, tapes)), Vec::new())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tm::build::{MAX_FIELD_WIDTH, TAPES};

    fn a_header() -> TmHeader {
        TmHeader::new(
            EncodingKind::Binary,
            16,
            3,
            Ty::List(Box::new(Ty::Nat)),
            vec![(REG, vec!['#', '0', '#']), (WORK, vec!['#', '0', '#'])],
        )
    }

    /// `ALL` is generated by the same macro invocation that declares the variants, so it cannot omit
    /// one. This test pins the consequences a caller depends on: every entry round-trips through
    /// `name`/`parse`, and no two entries share a name.
    #[test]
    fn all_lists_every_kind_and_round_trips() {
        assert!(!EncodingKind::ALL.is_empty());
        for &k in EncodingKind::ALL {
            assert_eq!(EncodingKind::parse(k.name()), Some(k), "`{}` does not round-trip", k.name());
        }
        let mut names: Vec<&str> = EncodingKind::ALL.iter().map(|k| k.name()).collect();
        names.sort_unstable();
        let before = names.len();
        names.dedup();
        assert_eq!(names.len(), before, "two encodings share a name");
    }

    #[test]
    fn encoding_kind_names_round_trip() {
        for &k in EncodingKind::ALL {
            assert_eq!(EncodingKind::parse(k.name()), Some(k));
        }
        assert_eq!(EncodingKind::parse("ternary"), None);
        assert_eq!(EncodingKind::parse("Unary"), None); // names are lowercase
    }

    /// The kind names the encoding AND the width instantiates it — both halves must reach the
    /// `Encoding` you get back, or the recipe describes a different machine than it claims.
    ///
    /// Iterates `EncodingKind::ALL` rather than naming `Unary`/`Binary` by hand, so a third row added
    /// to `encoding_kinds!` is checked here automatically instead of leaving this test covering two of
    /// three kinds while its assertions still read as general. In particular, this is what pins
    /// `at`'s doc claim that EVERY kind is BOUNDED (`field_width()` is always `Some`) — the property
    /// `run_tm_described` in `tm.rs` relies on to skip an unbounded branch.
    #[test]
    fn encoding_kind_instantiates_the_named_encoding_at_the_given_width() {
        for &k in EncodingKind::ALL {
            assert_eq!(k.at(8).field_width(), Some(8));
            assert_eq!(k.at(16).field_width(), Some(16));
            // BOUNDED: `field_width()` must be `Some` even at the largest width this build allows.
            assert!(k.at(MAX_FIELD_WIDTH).field_width().is_some());
        }
        // The kinds are distinguishable through the trait: a zero bank differs between them.
        assert_ne!(EncodingKind::Unary.at(8).init_reg(1), EncodingKind::Binary.at(8).init_reg(1));
    }

    /// An omitted `tape` line means "starts empty", so an explicitly-empty entry is not
    /// representable in the text form. Normalizing it away at construction is what makes the
    /// round-trip (property 2) exact rather than approximate.
    #[test]
    fn construction_drops_empty_tapes_and_orders_the_rest() {
        let h = TmHeader::new(
            EncodingKind::Unary,
            8,
            1,
            Ty::Nat,
            vec![(HEAP, vec![]), (WORK, vec!['#']), (REG, vec!['#', '_'])],
        );
        assert_eq!(h.tapes(), &[(REG, vec!['#', '_']), (WORK, vec!['#'])]);

        // The duplicate-index collapse `dedup_by_key` implements has been untested until now, though
        // `TmHeader::new` is `pub` and documents the behaviour. Neither entry here is empty, so the
        // empty-tape filter above does not interfere with either one — input order alone decides the
        // winner, and (per the corrected doc on `new`) the first entry survives.
        let h = TmHeader::new(EncodingKind::Unary, 8, 1, Ty::Nat, vec![(REG, vec!['#', 'a']), (REG, vec!['#', 'b'])]);
        assert_eq!(h.tapes().len(), 1, "duplicate indices must collapse to one entry");
        assert_eq!(h.tapes()[0], (REG, vec!['#', 'a']), "first survives when neither side is empty");
    }

    #[test]
    fn init_places_each_tape_at_its_index_and_leaves_the_rest_empty() {
        let init = a_header().init(TAPES);
        assert_eq!(init.len(), TAPES);
        assert_eq!(init[REG], vec!['#', '0', '#']);
        assert_eq!(init[WORK], vec!['#', '0', '#']);
        assert!(init[STACK].is_empty() && init[HEAP].is_empty() && init[BOX].is_empty());
    }

    /// `init` is asked for a tape count that comes from the FILE's `tapes N`, which need not match
    /// this compiler's `TAPES`. Out-of-range entries are dropped, not panicked on.
    #[test]
    fn init_is_total_for_any_tape_count() {
        assert_eq!(a_header().init(0).len(), 0);
        assert_eq!(a_header().init(1).len(), 1);
        assert_eq!(a_header().init(1)[0], vec!['#', '0', '#']);
        assert_eq!(a_header().init(64).len(), 64);
    }

    #[test]
    fn tape_names_cover_this_compilers_layout_and_nothing_else() {
        assert_eq!(tape_name(REG), Some("reg"));
        assert_eq!(tape_name(BOX), Some("box"));
        assert_eq!(tape_name(TAPES), None);
    }

    /// The header's canonical text. Order is FIXED even though the parser accepts any order — printing
    /// has to pick one, and a fixed one is what makes re-printing a re-parse idempotent.
    #[test]
    fn print_header_is_a_stable_listing_with_packed_tapes_and_named_comments() {
        let h = TmHeader::new(
            EncodingKind::Binary,
            4,
            2,
            Ty::List(Box::new(Ty::Nat)),
            vec![(REG, vec!['#', '0', '0', '0', '0', '#']), (WORK, vec!['#', '0', '0', '0', '0', '#'])],
        );
        let expected = "\
version 1
encoding binary
width 4
slots 2
result List<Nat>
tape 0 #0000#  ; reg
tape 1 #0000#  ; work
";
        assert_eq!(print_header(&h), expected);
    }

    /// D4: cells are PACKED, not space-separated. Rules use space-separated symbol lists because a
    /// rule's entries may be the wildcard `*`; a tape has no wildcards and `Symbol` is a `char`, so
    /// packing keeps a 120-cell bank on one readable line.
    #[test]
    fn tape_cells_are_packed_not_space_separated() {
        let h = TmHeader::new(EncodingKind::Unary, 4, 1, Ty::Nat, vec![(REG, vec!['#', '_', '_', '_', '_', '#'])]);
        assert!(print_header(&h).contains("tape 0 #____#"), "got:\n{}", print_header(&h));
        assert!(!print_header(&h).contains("# _ _"), "cells must not be space-separated");
    }

    /// A tape with no name still prints — the comment is a courtesy, the index is the address (D3).
    #[test]
    fn a_tape_beyond_this_compilers_layout_prints_without_a_comment() {
        let h = TmHeader::new(EncodingKind::Unary, 4, 1, Ty::Nat, vec![(9, vec!['#'])]);
        assert!(print_header(&h).contains("tape 9 #\n"), "got:\n{}", print_header(&h));
    }

    /// `parse_cells` is the inverse of the packed printing, and it stops at a comment.
    #[test]
    fn parse_cells_unpacks_and_stops_at_a_comment() {
        assert_eq!(parse_cells("#____#"), vec!['#', '_', '_', '_', '_', '#']);
        assert_eq!(parse_cells("#0000#  ; reg"), vec!['#', '0', '0', '0', '0', '#']);
        assert_eq!(parse_cells("   #1#   "), vec!['#', '1', '#']);
        assert_eq!(parse_cells(""), Vec::<Symbol>::new());
        assert_eq!(parse_cells("; only a comment"), Vec::<Symbol>::new());
    }
}
