/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_tapes = 2,
  anon_sym_start = 3,
  anon_sym_version = 4,
  anon_sym_encoding = 5,
  anon_sym_width = 6,
  anon_sym_slots = 7,
  anon_sym_result = 8,
  anon_sym_tape = 9,
  anon_sym_state = 10,
  anon_sym_COLON = 11,
  anon_sym_accept = 12,
  anon_sym_DASH_GT = 13,
  anon_sym_write = 14,
  anon_sym_COMMA = 15,
  anon_sym_move = 16,
  anon_sym_goto = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  anon_sym_STAR = 20,
  sym__symbol_char = 21,
  sym_head_move = 22,
  sym_number = 23,
  sym_comment = 24,
  sym_source_file = 25,
  sym__line = 26,
  sym_tapes = 27,
  sym_start = 28,
  sym__directive = 29,
  sym_version = 30,
  sym_encoding = 31,
  sym_width = 32,
  sym_slots = 33,
  sym_result = 34,
  sym_tape = 35,
  sym_state = 36,
  sym_rule = 37,
  sym_group = 38,
  sym_move_group = 39,
  sym_symbol = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_state_repeat1 = 42,
  aux_sym_group_repeat1 = 43,
  aux_sym_move_group_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_tapes] = "tapes",
  [anon_sym_start] = "start",
  [anon_sym_version] = "version",
  [anon_sym_encoding] = "encoding",
  [anon_sym_width] = "width",
  [anon_sym_slots] = "slots",
  [anon_sym_result] = "result",
  [anon_sym_tape] = "tape",
  [anon_sym_state] = "state",
  [anon_sym_COLON] = ":",
  [anon_sym_accept] = "accept",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_write] = "write",
  [anon_sym_COMMA] = ",",
  [anon_sym_move] = "move",
  [anon_sym_goto] = "goto",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_STAR] = "*",
  [sym__symbol_char] = "_symbol_char",
  [sym_head_move] = "head_move",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_tapes] = "tapes",
  [sym_start] = "start",
  [sym__directive] = "_directive",
  [sym_version] = "version",
  [sym_encoding] = "encoding",
  [sym_width] = "width",
  [sym_slots] = "slots",
  [sym_result] = "result",
  [sym_tape] = "tape",
  [sym_state] = "state",
  [sym_rule] = "rule",
  [sym_group] = "group",
  [sym_move_group] = "move_group",
  [sym_symbol] = "symbol",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_state_repeat1] = "state_repeat1",
  [aux_sym_group_repeat1] = "group_repeat1",
  [aux_sym_move_group_repeat1] = "move_group_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_tapes] = anon_sym_tapes,
  [anon_sym_start] = anon_sym_start,
  [anon_sym_version] = anon_sym_version,
  [anon_sym_encoding] = anon_sym_encoding,
  [anon_sym_width] = anon_sym_width,
  [anon_sym_slots] = anon_sym_slots,
  [anon_sym_result] = anon_sym_result,
  [anon_sym_tape] = anon_sym_tape,
  [anon_sym_state] = anon_sym_state,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_accept] = anon_sym_accept,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_write] = anon_sym_write,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_move] = anon_sym_move,
  [anon_sym_goto] = anon_sym_goto,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym__symbol_char] = sym__symbol_char,
  [sym_head_move] = sym_head_move,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_tapes] = sym_tapes,
  [sym_start] = sym_start,
  [sym__directive] = sym__directive,
  [sym_version] = sym_version,
  [sym_encoding] = sym_encoding,
  [sym_width] = sym_width,
  [sym_slots] = sym_slots,
  [sym_result] = sym_result,
  [sym_tape] = sym_tape,
  [sym_state] = sym_state,
  [sym_rule] = sym_rule,
  [sym_group] = sym_group,
  [sym_move_group] = sym_move_group,
  [sym_symbol] = sym_symbol,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_state_repeat1] = aux_sym_state_repeat1,
  [aux_sym_group_repeat1] = aux_sym_group_repeat1,
  [aux_sym_move_group_repeat1] = aux_sym_move_group_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_tapes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_start] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_encoding] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_width] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_slots] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_result] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tape] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_state] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_accept] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_write] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_move] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_goto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym__symbol_char] = {
    .visible = false,
    .named = true,
  },
  [sym_head_move] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_tapes] = {
    .visible = true,
    .named = true,
  },
  [sym_start] = {
    .visible = true,
    .named = true,
  },
  [sym__directive] = {
    .visible = false,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_encoding] = {
    .visible = true,
    .named = true,
  },
  [sym_width] = {
    .visible = true,
    .named = true,
  },
  [sym_slots] = {
    .visible = true,
    .named = true,
  },
  [sym_result] = {
    .visible = true,
    .named = true,
  },
  [sym_tape] = {
    .visible = true,
    .named = true,
  },
  [sym_state] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_move_group] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_state_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_move_group_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_cells = 1,
  field_index = 2,
  field_move = 3,
  field_name = 4,
  field_read = 5,
  field_target = 6,
  field_type = 7,
  field_write = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_cells] = "cells",
  [field_index] = "index",
  [field_move] = "move",
  [field_name] = "name",
  [field_read] = "read",
  [field_target] = "target",
  [field_type] = "type",
  [field_write] = "write",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_target, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_type, 1},
  [3] =
    {field_index, 1},
  [4] =
    {field_cells, 2},
    {field_index, 1},
  [6] =
    {field_move, 6},
    {field_read, 0},
    {field_target, 9},
    {field_write, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == ',') ADVANCE(9);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '[') ADVANCE(10);
      if (lookahead == ']') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == ']') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != '[') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == ',') ADVANCE(8);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(7);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '[') ADVANCE(10);
      if (lookahead == ']') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '*' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(16);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '*' &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(16);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__symbol_char);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__symbol_char);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '*' &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '*' &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'e', 2,
        'g', 3,
        'm', 4,
        'r', 5,
        's', 6,
        't', 7,
        'v', 8,
        'w', 9,
        'L', 10,
        'R', 10,
        'S', 10,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_head_move);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'v') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(39);
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_goto);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_move);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 38:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_tape);
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 43:
      if (lookahead == 'h') ADVANCE(53);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(56);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_slots);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_start);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_state);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_tapes);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_width);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_write);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_accept);
      END_STATE();
    case 56:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_result);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 59:
      if (lookahead == 'g') ADVANCE(61);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_version);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_encoding);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_tapes] = ACTIONS(1),
    [anon_sym_start] = ACTIONS(1),
    [anon_sym_version] = ACTIONS(1),
    [anon_sym_encoding] = ACTIONS(1),
    [anon_sym_width] = ACTIONS(1),
    [anon_sym_slots] = ACTIONS(1),
    [anon_sym_result] = ACTIONS(1),
    [anon_sym_tape] = ACTIONS(1),
    [anon_sym_state] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_accept] = ACTIONS(1),
    [anon_sym_write] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_move] = ACTIONS(1),
    [anon_sym_goto] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym__symbol_char] = ACTIONS(1),
    [sym_head_move] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(30),
    [sym__line] = STATE(2),
    [sym_tapes] = STATE(2),
    [sym_start] = STATE(2),
    [sym__directive] = STATE(2),
    [sym_version] = STATE(2),
    [sym_encoding] = STATE(2),
    [sym_width] = STATE(2),
    [sym_slots] = STATE(2),
    [sym_result] = STATE(2),
    [sym_tape] = STATE(2),
    [sym_state] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_tapes] = ACTIONS(7),
    [anon_sym_start] = ACTIONS(9),
    [anon_sym_version] = ACTIONS(11),
    [anon_sym_encoding] = ACTIONS(13),
    [anon_sym_width] = ACTIONS(15),
    [anon_sym_slots] = ACTIONS(17),
    [anon_sym_result] = ACTIONS(19),
    [anon_sym_tape] = ACTIONS(21),
    [anon_sym_state] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym_tapes] = STATE(3),
    [sym_start] = STATE(3),
    [sym__directive] = STATE(3),
    [sym_version] = STATE(3),
    [sym_encoding] = STATE(3),
    [sym_width] = STATE(3),
    [sym_slots] = STATE(3),
    [sym_result] = STATE(3),
    [sym_tape] = STATE(3),
    [sym_state] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_tapes] = ACTIONS(7),
    [anon_sym_start] = ACTIONS(9),
    [anon_sym_version] = ACTIONS(11),
    [anon_sym_encoding] = ACTIONS(13),
    [anon_sym_width] = ACTIONS(15),
    [anon_sym_slots] = ACTIONS(17),
    [anon_sym_result] = ACTIONS(19),
    [anon_sym_tape] = ACTIONS(21),
    [anon_sym_state] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym_tapes] = STATE(3),
    [sym_start] = STATE(3),
    [sym__directive] = STATE(3),
    [sym_version] = STATE(3),
    [sym_encoding] = STATE(3),
    [sym_width] = STATE(3),
    [sym_slots] = STATE(3),
    [sym_result] = STATE(3),
    [sym_tape] = STATE(3),
    [sym_state] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_tapes] = ACTIONS(29),
    [anon_sym_start] = ACTIONS(32),
    [anon_sym_version] = ACTIONS(35),
    [anon_sym_encoding] = ACTIONS(38),
    [anon_sym_width] = ACTIONS(41),
    [anon_sym_slots] = ACTIONS(44),
    [anon_sym_result] = ACTIONS(47),
    [anon_sym_tape] = ACTIONS(50),
    [anon_sym_state] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_tape,
    ACTIONS(60), 1,
      anon_sym_accept,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    STATE(31), 1,
      sym_group,
    STATE(5), 2,
      sym_rule,
      aux_sym_state_repeat1,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [31] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    ACTIONS(66), 1,
      anon_sym_tape,
    STATE(31), 1,
      sym_group,
    STATE(6), 2,
      sym_rule,
      aux_sym_state_repeat1,
    ACTIONS(64), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [59] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_tape,
    ACTIONS(72), 1,
      anon_sym_LBRACK,
    STATE(31), 1,
      sym_group,
    STATE(6), 2,
      sym_rule,
      aux_sym_state_repeat1,
    ACTIONS(68), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [87] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 9,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_tape,
      anon_sym_state,
  [108] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_tape,
    ACTIONS(81), 10,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
      anon_sym_LBRACK,
  [127] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_tape,
    ACTIONS(85), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [145] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_tape,
    ACTIONS(89), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [163] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_tape,
    ACTIONS(93), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [181] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_tape,
    ACTIONS(97), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [199] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_tape,
    ACTIONS(101), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [217] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_tape,
    ACTIONS(105), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [235] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_tape,
    ACTIONS(109), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_tape,
    ACTIONS(64), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [271] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_tape,
    ACTIONS(113), 9,
      ts_builtin_sym_end,
      anon_sym_tapes,
      anon_sym_start,
      anon_sym_version,
      anon_sym_encoding,
      anon_sym_width,
      anon_sym_slots,
      anon_sym_result,
      anon_sym_state,
  [289] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_RBRACK,
    ACTIONS(119), 2,
      anon_sym_STAR,
      sym__symbol_char,
    STATE(19), 2,
      sym_symbol,
      aux_sym_group_repeat1,
  [304] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACK,
    ACTIONS(119), 2,
      anon_sym_STAR,
      sym__symbol_char,
    STATE(20), 2,
      sym_symbol,
      aux_sym_group_repeat1,
  [319] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
    ACTIONS(125), 2,
      anon_sym_STAR,
      sym__symbol_char,
    STATE(20), 2,
      sym_symbol,
      aux_sym_group_repeat1,
  [334] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
    ACTIONS(130), 1,
      sym_head_move,
    STATE(24), 1,
      aux_sym_move_group_repeat1,
  [347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 3,
      anon_sym_RBRACK,
      anon_sym_STAR,
      sym__symbol_char,
  [356] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_RBRACK,
    ACTIONS(136), 1,
      sym_head_move,
    STATE(23), 1,
      aux_sym_move_group_repeat1,
  [369] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_RBRACK,
    ACTIONS(141), 1,
      sym_head_move,
    STATE(23), 1,
      aux_sym_move_group_repeat1,
  [382] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
  [390] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
  [398] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LBRACK,
    STATE(43), 1,
      sym_move_group,
  [408] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    STATE(40), 1,
      sym_group,
  [418] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_number,
  [425] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
  [432] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_DASH_GT,
  [439] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_number,
  [446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_identifier,
  [453] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_number,
  [460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_number,
  [467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_write,
  [474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_identifier,
  [481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_number,
  [488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_COLON,
  [495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_COMMA,
  [502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_move,
  [509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COMMA,
  [516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
  [523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_goto,
  [530] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
  [537] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_identifier,
  [544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_identifier,
  [551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 31,
  [SMALL_STATE(6)] = 59,
  [SMALL_STATE(7)] = 87,
  [SMALL_STATE(8)] = 108,
  [SMALL_STATE(9)] = 127,
  [SMALL_STATE(10)] = 145,
  [SMALL_STATE(11)] = 163,
  [SMALL_STATE(12)] = 181,
  [SMALL_STATE(13)] = 199,
  [SMALL_STATE(14)] = 217,
  [SMALL_STATE(15)] = 235,
  [SMALL_STATE(16)] = 253,
  [SMALL_STATE(17)] = 271,
  [SMALL_STATE(18)] = 289,
  [SMALL_STATE(19)] = 304,
  [SMALL_STATE(20)] = 319,
  [SMALL_STATE(21)] = 334,
  [SMALL_STATE(22)] = 347,
  [SMALL_STATE(23)] = 356,
  [SMALL_STATE(24)] = 369,
  [SMALL_STATE(25)] = 382,
  [SMALL_STATE(26)] = 390,
  [SMALL_STATE(27)] = 398,
  [SMALL_STATE(28)] = 408,
  [SMALL_STATE(29)] = 418,
  [SMALL_STATE(30)] = 425,
  [SMALL_STATE(31)] = 432,
  [SMALL_STATE(32)] = 439,
  [SMALL_STATE(33)] = 446,
  [SMALL_STATE(34)] = 453,
  [SMALL_STATE(35)] = 460,
  [SMALL_STATE(36)] = 467,
  [SMALL_STATE(37)] = 474,
  [SMALL_STATE(38)] = 481,
  [SMALL_STATE(39)] = 488,
  [SMALL_STATE(40)] = 495,
  [SMALL_STATE(41)] = 502,
  [SMALL_STATE(42)] = 509,
  [SMALL_STATE(43)] = 516,
  [SMALL_STATE(44)] = 523,
  [SMALL_STATE(45)] = 530,
  [SMALL_STATE(46)] = 537,
  [SMALL_STATE(47)] = 544,
  [SMALL_STATE(48)] = 551,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state, 3, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state, 3, 0, 2),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state, 4, 0, 2),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state, 4, 0, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_state_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_state_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tape, 2, 0, 4),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tape, 2, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 10, 0, 6),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 10, 0, 6),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start, 2, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start, 2, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_encoding, 2, 0, 2),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_encoding, 2, 0, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_width, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_width, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tapes, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tapes, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_result, 2, 0, 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_result, 2, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_version, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tape, 3, 0, 5),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tape, 3, 0, 5),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slots, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slots, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_move_group_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_move_group_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [151] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_move_group, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_move_group, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_redextape_tm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "redextape_tm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
