#![cfg(feature = "cranelift")]
//! The native oracle: for every first-order demo, the reference tree-walker's value, the decoded λ
//! normal form, the decoded TM final tape UNDER EVERY ENCODING, and the decoded native (Cranelift JIT)
//! result all agree. This extends `redextape-core`'s three-way oracle (`tests/three_way_oracle.rs`)
//! with native as a validated leg.
//!
//! Native's PRIMARY new cross-check is narrower and sharper than the four-way: `native == asm-interp`
//! on the SAME lowered `Program` isolates codegen (`run_native`/Cranelift) from interpretation
//! (`run_asm`) — both share `lower_asm`/`defunc`, so any disagreement is a real codegen bug, not a
//! front-end or lowering difference.
//!
//! ONE TEST PER ENCODING, not one test doing every encoding: `four_way_tests!` emits
//! `four_way_oracle_on_the_first_order_suite_{unary,binary}`, so each emitted test is still genuinely
//! FOUR-way (reference == λ == TM(one encoding) == native) and its name states its real arity. It is
//! this FILE that covers five legs — reference, λ, TM-unary, TM-binary, native — not any single test.
//! LEGS, not "backends": two of the five are the same TM backend at different encodings, the
//! distinction this file polices elsewhere (`the_tm_reports_its_ceiling_on_the_same_demos`'s "SCOPED TO
//! UNARY" note, `past_the_u64_ceiling_the_backends_diverge_by_design`'s "a claim about the TM BACKEND,
//! not about one encoding").
//!
//! WHAT ACTUALLY FORCES A DEVELOPER HERE, stated precisely rather than implied end-to-end: adding a
//! third `EncodingKind` breaks `tm_leg`'s match below (no wildcard arm) at COMPILE TIME, and that is
//! one forcing function — the new arm is required to compile, so an edit to THIS FILE is unavoidable.
//! `encodings()` (above) is no longer a second, unenforced registration point: it now DERIVES from
//! `EncodingKind::ALL`, generated by the same `encoding_kinds!` invocation (`tm/header.rs`) that
//! declares the variants, so a new row reaches `encodings()` without anyone editing THAT FUNCTION —
//! which is a narrower claim than "without editing this file", and the narrower one is the true one.
//! `every_encoding_has_a_four_way_test` still derives its
//! expectation from `encodings()` AT RUNTIME and compares it against `EMITTED`, so it still catches
//! drift BETWEEN THOSE TWO LISTS — a generated test deleted, or the `four_way_tests!` invocation below
//! left stale. What changed is that `encodings()` can no longer itself fall behind `EncodingKind::ALL`:
//! the chain from a new row in `encoding_kinds!` to this file's coverage guard is closed end to end, so
//! the one thing still requiring a developer's hand here is the `four_way_tests!` macro invocation
//! itself — see `every_encoding_has_a_four_way_test`'s own doc comment below for the same statement at
//! its point of use.
//!
//! THE UNARY LEG RUNS AT THE FIXED `MAX_FIELD_WIDTH` (64) it has always run at, while binary goes
//! through `run_tm_fitted`. The asymmetry is DELIBERATE CONVENTION, not a correctness requirement —
//! see `tm_leg`'s doc comment below for the full statement and its citation.
//!
//! Two things `tm_leg`'s doc does not cover, both about why UNARY in particular stays fixed rather than
//! also being fitted (considered and rejected, so a future editor does not "fix" it): fitting unary
//! would silently move every demo from a 64-cell bank to an 8-16-cell one, a LATERAL coverage change
//! (fitted exercises narrow banks and the overflow boundary; fixed-64 exercises wide banks — neither
//! dominates) to checks that were already green. And the width axis itself is not this file's job:
//! `tm_width_equivalence.rs` and `tm_bank_invariant.rs` already own it, running `widths() x
//! encodings_at(width)` deliberately across the full range; this file checks native agreement at one
//! width per encoding, the same split core's `three_way_oracle.rs` uses.
//!
//! NATIVE'S DISTINCTIVE CAPABILITY, stated at the width it actually holds. Native compiles to real
//! 64-bit machine registers and has no `MAX_FIELD_WIDTH` ceiling. That is a contrast with UNARY, not
//! with the TM backend: a `w`-cell binary field holds `0..2^w`, so at 64 cells `Binary` covers the
//! entire `u64` range. Both halves are now MEASURED rather than asserted in prose —
//! `the_tm_reports_its_ceiling_on_the_same_demos` pins unary reporting `Overflow` on
//! `BEYOND_FIELD_WIDTH_DEMOS` (the control), and `binary_runs_the_demos_unary_cannot_represent` pins
//! binary running the same four and agreeing with the reference (measured: all four fit at width 16).
//!
//! PAST 2^64 THE BACKENDS DIVERGE BY DESIGN, and that is pinned rather than left unexercised — see
//! `past_the_u64_ceiling_the_backends_diverge_by_design` and `SATURATION_DEMOS`. It cannot be an
//! agreement test: the reference and native SATURATE to `u64::MAX` (`tm/asm.rs`'s
//! `saturating_add`/`saturating_mul`), while the TM halts in its rule-less overflow guard
//! (`tm/lower_tm.rs`'s `Builder::overflow`) at every width up to the ceiling. Both are deliberate.
//!
//! CAPS NOTE (Task 4/5 review): native's step accounting is coarse (it only ticks loop back-edges and
//! calls, enough to guarantee termination, not to match `run_asm`'s per-instruction step count). Every
//! program here uses `DEFAULT_CAPS`/`TM_DEFAULT_CAPS` (generous) and terminates well within them, so a
//! tight cap never produces a spurious cross-backend "disagreement".

use proptest::prelude::*;
use redextape_core::core::Core;
use redextape_core::desugar::desugar;
use redextape_core::lambda::{LambdaRun, MAX_REDUCTION_STEPS, decode, run_lambda};
use redextape_core::parser::parse;
use redextape_core::tm::{
    AsmRun, Binary, DEFAULT_CAPS, Encoding, EncodingKind, LowerError, MAX_FIELD_WIDTH, Program, TM_DEFAULT_CAPS, TmRun,
    Unary, decode_asm, decode_tape, defunc, lower_asm, run_asm, run_tm, run_tm_fitted,
};
use redextape_core::value::Value;
use redextape_core::{RunError, run};
use redextape_native::{NativeRun, run_native};
use redextape_test_support::arb_expr_over;

/// Parse + desugar `src` to Core, panicking on a parse error (every demo string here is known-good).
fn core_of(src: &str) -> Core {
    let (prog, ds) = parse(src);
    assert!(ds.is_empty(), "parse errors for `{src}`: {ds:?}");
    desugar(&prog.unwrap())
}

/// Mirrors `redextape_core::tm`'s own (private) `lower_program` template exactly: try `lower_asm`
/// first (first-order Core unchanged); only retry through `defunc` when it rejects the program as
/// higher-order (`LowerError::Unsupported`). `run_native` uses this same template internally
/// (it is not exported, so this is a deliberate, documented duplicate) — see this crate's `lib.rs`.
fn lower_program(core: &Core) -> Result<Program, LowerError> {
    match lower_asm(core) {
        Ok(p) => return Ok(p),
        Err(LowerError::Unsupported { .. }) => {}
        Err(e @ LowerError::TooDeep { .. }) => return Err(e),
    }
    let defunced = defunc(core)?;
    lower_asm(&defunced)
}

/// Every encoding this file's TM leg covers. THE single place that decides — the coverage guard
/// (`every_encoding_has_a_four_way_test`) derives its expectation from here rather than from a second
/// hard-coded list, because a guard that restates the list it is checking checks nothing.
///
/// Derives from `EncodingKind::ALL`, so this list itself cannot fall behind the enum — see the module
/// doc's rewritten paragraph on what that does and does not close.
fn encodings() -> Vec<(&'static str, EncodingKind)> {
    EncodingKind::ALL.iter().map(|&k| (k.name(), k)).collect()
}

/// The `EncodingKind` that `encodings()` gives this name. This function never sees a TEST's name — it
/// receives the encoding string `four_way_tests!` passes as `$enc` — so it panics only when that string
/// is not a key in `encodings()`. It does NOT catch a generated test's function name drifting from what
/// it actually runs (e.g. the macro's `..._binary => "unary"` swapped): that would still find a real
/// entry in `encodings()` and pass, with a test named for one encoding silently running the other.
fn encoding_named(name: &str) -> EncodingKind {
    encodings()
        .into_iter()
        .find(|(n, _)| *n == name)
        .unwrap_or_else(|| panic!("no encoding named `{name}` in `encodings()`"))
        .1
}

/// Run the TM leg for `kind`, returning the outcome AND the encoding its tape must be DECODED with.
///
/// The two encodings run differently, but the asymmetry is a DELIBERATE CONVENTION plus the
/// additive-only constraint of the branch that made Binary a participating leg here
/// (`binary-oracle-leg-and-collision-doc`), NOT a correctness requirement. Unary runs at the fixed
/// `MAX_FIELD_WIDTH` (64) that `Unary::default()` gives — the width this file's TM leg has always used,
/// kept unchanged so that adding binary alters no assertion that was already green.
///
/// Binary goes through `run_tm_fitted`, but NOT because decode needs the fit width: both decoders are
/// structural now, so a default-width (64) `Binary` would decode a fitted-at-16 tape correctly too —
/// `a_tape_decodes_the_same_at_every_reader_width` (`redextape-core/src/tm.rs`) pins exactly that. The
/// fitted form is kept because the width it settles on is worth naming (it is the number
/// `binary_runs_the_demos_unary_cannot_represent` reports — all four of its demos fit at 16), because it
/// keeps `at_width` on this file's executed path, and because it matches the convention core's
/// `three_way_oracle.rs` already uses, so the two files do not drift.
///
/// So: do not "fix" the unary arm into a fitted one believing decode demands it, and do not read the
/// binary arm as load-bearing for correctness — it is convention, not requirement.
fn tm_leg(core: &Core, kind: EncodingKind) -> (TmRun, Box<dyn Encoding>) {
    match kind {
        EncodingKind::Unary => (run_tm(core, &Unary::default(), TM_DEFAULT_CAPS), Box::new(Unary::default())),
        EncodingKind::Binary => {
            let (run, width) = run_tm_fitted(core, &Binary::default(), TM_DEFAULT_CAPS);
            // `width` is `None` in two cases: an unbounded encoding (not `Binary` — its
            // `field_width()` is always `Some`), or a lowering failure (`run_tm_fitted` returns
            // early with `(e, None)` before ever picking a width). In the second case `run` is
            // already the error `TmRun` (`LowerError`/`TooLarge`), not `Ran`, so the width chosen
            // here is never read for decoding — fall back to `Binary::default()`'s own width
            // (`MAX_FIELD_WIDTH`) instead of panicking, and let the error flow to the caller.
            (run, EncodingKind::Binary.at(width.unwrap_or(MAX_FIELD_WIDTH)))
        }
    }
}

/// reference == λ == TM(`kind`) == native, guided by the reference value's type. All four must run to
/// a value that decodes equal.
///
/// Still genuinely FOUR-way after the per-encoding split, and that is not an accident of naming: each
/// emitted test runs ONE encoding, so its name states its real arity. It is the FILE that now covers
/// five legs, not any single test — see the module doc's "LEGS, not backends" note.
fn assert_four_way(src: &str, kind: EncodingKind) {
    let reference = run(src).unwrap_or_else(|e| panic!("reference run failed for `{src}`: {e:?}"));
    let core = core_of(src);
    let lambda = run_lambda(&core, MAX_REDUCTION_STEPS);
    let (tm, tm_enc) = tm_leg(&core, kind);
    let native = run_native(&core, DEFAULT_CAPS);
    match (lambda, tm, native) {
        (LambdaRun::Reduced(nf), TmRun::Ran { tapes }, NativeRun::Ran(outcome)) => {
            assert_eq!(decode(&nf, &reference), Some(reference.clone()), "reference vs λ disagree for: {src}");
            assert_eq!(
                decode_tape(&tapes, &reference, &*tm_enc),
                Some(reference.clone()),
                "reference vs {}-TM disagree for: {src}",
                kind.name()
            );
            assert_eq!(
                decode_asm(&outcome, &reference),
                Some(reference.clone()),
                "reference vs native disagree for: {src}"
            );
        }
        (l, t, n) => panic!(
            "four-way oracle mismatch for {src} ({}):\n  reference={reference:?}\n  lambda={l:?}\n  tm={t:?}\n  native={n:?}",
            kind.name()
        ),
    }
}

/// Native's primary new cross-check: `run_native` and `run_asm` on the SAME lowered `Program` decode
/// to the same `Value`. Since both share `lower_asm`/`defunc`, this isolates codegen (compile) from
/// interpretation.
fn assert_native_matches_asm(src: &str) {
    let reference = run(src).unwrap_or_else(|e| panic!("reference run failed for `{src}`: {e:?}"));
    let core = core_of(src);
    let prog = lower_program(&core).unwrap_or_else(|e| panic!("lowering failed for `{src}`: {e:?}"));
    let asm = run_asm(&prog, DEFAULT_CAPS);
    let native = run_native(&core, DEFAULT_CAPS);
    match (asm, native) {
        (AsmRun::Ran(asm_outcome), NativeRun::Ran(native_outcome)) => {
            let asm_val = decode_asm(&asm_outcome, &reference);
            assert_eq!(asm_val, Some(reference.clone()), "asm-interp vs reference disagree for: {src}");
            let native_val = decode_asm(&native_outcome, &reference);
            assert_eq!(native_val, asm_val, "native vs asm-interp disagree for: {src}");
        }
        (a, n) => panic!("native vs asm-interp mismatch for {src}:\n  asm={a:?}\n  native={n:?}"),
    }
}

/// native == reference only (no TM leg — the TM's fixed-width UNARY tape cannot represent these
/// values; the TM's `Binary` encoding could represent every value used below, since none reaches 2⁶⁴ —
/// see `binary_runs_the_demos_unary_cannot_represent` and `the_tm_reports_its_ceiling_on_the_same_demos`
/// below). Native's distinctive capability: real 64-bit registers, no `MAX_FIELD_WIDTH` (64) ceiling at
/// ANY encoding.
fn assert_native_matches_reference(src: &str) {
    let reference = run(src).unwrap_or_else(|e| panic!("reference run failed for `{src}`: {e:?}"));
    let core = core_of(src);
    match run_native(&core, DEFAULT_CAPS) {
        NativeRun::Ran(outcome) => {
            assert_eq!(
                decode_asm(&outcome, &reference),
                Some(reference.clone()),
                "native vs reference disagree for: {src}"
            );
        }
        other => panic!("native did not run `{src}`: {other:?}"),
    }
}

/// The first-order demo suite (a subset of `redextape-core`'s `three_way_oracle.rs`
/// `FIRST_ORDER_DEMOS`) — arithmetic, monus, comparison, if, let/let-mut/assign/while, calls &
/// recursion, list construction & access, higher-order programs (`defunc`), and mutually recursive /
/// forward-referencing `fn`s (`Core::LetRecGroup`) — every value stays « MAX_FIELD_WIDTH (64) so the TM
/// leg can participate too.
const FIRST_ORDER_DEMOS: &[&str] = &[
    "1 + 2 * 3",
    "3 - 5",
    "if 2 > 1 { 10 } else { 20 }",
    "if 1 == 2 { 10 } else { 20 }",
    "let x = 40; x + 2",
    "let x = 1; let y = x + x; y * 3",
    "let mut x = 1; x = x + 10; x = x * 2; x",
    "let mut n = 4; let mut acc = 0; while n > 0 { acc = acc + 1; n = n - 1; } acc",
    "let add1 = |x| x + 1; add1(41)",
    "fn sum(n) { if n == 0 { 0 } else { n + sum(n - 1) } } sum(5)",
    "fn count_down(n) { let mut acc = 0; while n > 0 { acc = acc + 1; n = n - 1; } acc } count_down(4)",
    "fn add1(x) { x + 1 } fn pair_sum(a, b) { a + b } pair_sum(1, add1(2))",
    "is_empty(nil)",
    "is_empty(cons(1, nil))",
    "[1, 2, 3]",
    "cons(1, cons(2, nil))",
    "head(cons(7, nil))",
    "tail(cons(7, nil))",
    "head(cons(1, cons(2, nil)))",
    "tail(cons(1, cons(2, nil)))",
    "head(tail(cons(1, cons(2, nil))))",
    "head([1, 2, 3])",
    "tail([1, 2, 3])",
    // Higher-order: a function received as a value, defunctionalized before lowering.
    "fn apply2(f, x) { f(x) } fn add1(x) { x + 1 } apply2(add1, 5)",
    "fn map(xs, f) { if is_empty(xs) { nil } else { cons(f(head(xs)), map(tail(xs), f)) } } fn add1(x) { x + 1 } [3, 1, 2].map(add1)",
    // Higher-order with immutable capture: `|x| x + n` captures `n` by value.
    "let n = 5; fn map(xs, f) { if is_empty(xs) { nil } else { cons(f(head(xs)), map(tail(xs), f)) } } [1, 2, 3].map(|x| x + n)",
    "\
        fn map(xs, f) { if is_empty(xs) { nil } else { cons(f(head(xs)), map(tail(xs), f)) } }\n\
        fn fold(xs, acc, f) { if is_empty(xs) { acc } else { fold(tail(xs), f(acc, head(xs)), f) } }\n\
        fn add(a, b) { a + b }\n\
        fn add1(x) { x + 1 }\n\
        fold([3, 1, 2].map(add1), 0, add)",
    // Higher-order currying: a value-lambda whose body is ANOTHER value-lambda.
    "fn ap(f, x) { f(x) } let add = |y| |z| y + z; ap(ap(add, 4), 5)",
    // MUTUAL RECURSION (`Core::LetRecGroup`) — the same three programs `redextape-core`'s
    // `three_way_oracle.rs` adds, carried here so the design spec's `reference == λ == TM == native`
    // claim is ASSERTED on this class rather than assumed from the three-way leg. Each member is
    // observably different at every level, so a permuted group computes a wrong value, not a crash.
    "fn is_even(n){ if n == 0 { true } else { is_odd(n - 1) } } \
     fn is_odd(n){ if n == 0 { false } else { is_even(n - 1) } } is_even(4)",
    // The ODD argument is not a duplicate: its answer comes out of the OTHER member's base case, so a
    // backend that collapsed the pair onto `is_even` (which still answers `true` at every even
    // argument) is caught here and not by the even case.
    "fn is_even(n){ if n == 0 { true } else { is_odd(n - 1) } } \
     fn is_odd(n){ if n == 0 { false } else { is_even(n - 1) } } is_even(5)",
    // A forward reference with no cycle: `a` is a one-member component still emitted INSIDE `b`.
    "fn a(n){ b(n) + 1 } fn b(n){ n * 2 } a(3)",
    // Three members, not two: 1+2+4+1 = 8 identifies the exact rotation of the cycle.
    "fn s0(n){ if n == 0 { 0 } else { 1 + s1(n - 1) } } \
     fn s1(n){ if n == 0 { 0 } else { 2 + s2(n - 1) } } \
     fn s2(n){ if n == 0 { 0 } else { 4 + s0(n - 1) } } s0(4)",
    // A group reaching the backends THROUGH `defunc` (`id` is used as a value), and a forward
    // reference doing the same — the paths every case above skips, since they lower via `lower_asm`
    // directly. See the matching comment in `three_way_oracle.rs`.
    "fn ev(n,k){ if n == 0 { k(1) } else { od(n - 1, k) } } \
     fn od(n,k){ if n == 0 { k(0) } else { ev(n - 1, k) } } fn id(x){ x } ev(4, id)",
    "fn ev(n,k){ if n == 0 { k(1) } else { od(n - 1, k) } } \
     fn od(n,k){ if n == 0 { k(0) } else { ev(n - 1, k) } } fn id(x){ x } ev(3, id)",
    "fn ap(h,x){ h(x) } fn f(n){ ap(g, n) } fn g(n){ n + 1 } f(3)",
    // A fn both CALLED BY NAME and USED AS A VALUE. Previously `Unsupported` on TM and native while
    // the reference and λ accepted it — an oracle asymmetry this class now closes.
    // Non-commutative at arity 2, so a forwarder with swapped arguments cannot pass: 5 + 7 = 12.
    "fn sub(a, b) { a - b } fn ap2(g, a, b) { g(a, b) } sub(9, 4) + ap2(sub, 10, 3)",
    // RECURSIVE and value-used — the case the restriction actually blocked, and the reason the class
    // is large: `analyze` counts a self-call as `name_called`, so every recursive fn used as a value
    // was BOTH. 10 + 3 = 13.
    "fn sum(n) { if n == 0 { 0 } else { n + sum(n - 1) } } fn ap(g, x) { g(x) } ap(sum, 4) + sum(2)",
    // `map` itself passed as a value while ALSO being called by name. Its body dispatches at arity 1
    // and it is value-used at arity 2, so the two dispatchers are distinct. `map` calls itself by
    // name, so the plain call graph has a cycle through `map` -- the interesting claim is about the
    // DISPATCHER graph instead: `$apply2 -> map -> $apply1 -> add1` has no cycle through dispatchers.
    // 2 + 6 = 8.
    "fn map(xs, f) { if is_empty(xs) { nil } else { cons(f(head(xs)), map(tail(xs), f)) } }\n\
     fn add1(x) { x + 1 }\n\
     fn ap2(g, a, b) { g(a, b) }\n\
     head(map([1, 2], add1)) + head(ap2(map, [5, 6], add1))",
    // A forwarding arm (BOTH: `b`, called by name AND used as a value) SHARING one dispatcher with a
    // normal arm (value-only: `v`), at BOTH possible tag positions. Every BOTH demo above has its
    // forwarder as the SOLE arm of its `$applyN`, so a per-arm parameter-binding defect -- the
    // forwarder must bind NO params so `$a_i` reaches the call directly, while a normal arm must bind
    // its own -- would compile and pass unnoticed. Tags are assigned in declaration order per arity:
    // in the first program below `v` is tag 0 (normal arm) and `b` is tag 1 (forwarder); in the
    // second, the two `fn`s are declared in the opposite order, so `b` is tag 0 (forwarder) and `v`
    // is tag 1 (normal arm) -- confirmed by dumping the lowered asm, not assumed. `v` (x*10) and `b`
    // (x+1) are value-distinguishable, so a tag mix-up or a mis-bound param changes the answer rather
    // than staying silent: 10 + 2 + 6 = 18.
    "fn v(x) { x * 10 } fn b(x) { x + 1 } fn ap(g, x) { g(x) } ap(v, 1) + ap(b, 1) + b(5)",
    "fn b(x) { x + 1 } fn v(x) { x * 10 } fn ap(g, x) { g(x) } ap(v, 1) + ap(b, 1) + b(5)",
    // A user `fn` shadowing a list builtin. `defunc` synthesizes `$head($clos)` for its dispatcher
    // tag test, and `lower_asm` resolves a bound function BEFORE the builtin table — so with the
    // bare name this silently miscompiled (measured at 3246742: reference 5, λ 5, TM 3). The `$`
    // form is unforgeable in user source, so scaffolding is uncapturable. 2 + 3 = 5.
    "fn head(x) { x + 1 } fn ap(g, x) { g(x) } fn add1(y) { y + 1 } head(1) + ap(add1, 2)",
    // The same shadowing where the shadowing function is ALSO the value being dispatched. 2 + 3 = 5.
    "fn head(x) { x + 1 } fn ap(g, x) { g(x) } head(1) + ap(head, 2)",
    // A user `fn tail` shadowing the builtin — but unlike the `head` pair above, a `tail`-shaped
    // twin of THAT demo (`fn tail(x){x+1} fn ap(g,x){g(x)} tail(1)+ap(tail,2)`) is VACUOUS: `$head`
    // is called unconditionally by every dispatcher (the tag test), but `$tail` is only called by
    // `tail1()` to unpack a dispatcher arm's CAPTURED env, and that program's closures capture
    // nothing, so `tail1()` is never invoked and the demo could not detect a reverted `$tail`->`tail`
    // regression (found when this class was surveyed for Task 2). Here `tail` is BOTH called by name
    // (`tail(3)`) and used as a value (`ap(tail, 2)`), so it is KEPT — a real top-level `tail` binder
    // exists for scaffolding to collide with — and the sibling value-lambda `|y| y + n` at the SAME
    // arity captures `n`, forcing its dispatcher arm to call `tail1()` to unpack `$env`. Confirmed
    // non-vacuous by sabotage (reverting `tail1`'s emitted name to the bare `"tail"`): the TM diverges
    // (`HitCap`) while reference and λ still agree. 4 + 3 + 12 = 19.
    "let n = 7; fn tail(x) { x + 1 } fn ap(g, y) { g(y) } tail(3) + ap(tail, 2) + ap(|y| y + n, 5)",
    // `nil` is the FOURTH synthesized scaffolding name (the closed-function-value closure's env, the
    // dispatcher's fault sentinel, the env-list terminator), and `rewrite_value_name`'s bare-`"nil"`
    // check used to short-circuit BEFORE its `tags` check — so a user `fn nil`, itself USED AS A
    // VALUE, compiled to the empty list instead of `cons(tag, $nil)`, and the dispatcher's
    // `$head($clos)` tag test then faulted on it. `nil` is not a keyword in this language (see
    // `prelude.rs`'s module doc), so a user `fn nil` SHADOWS the empty list exactly as the reference
    // interpreter's frame lookup does — confirmed against the reference, which evaluates this to 5.
    // Confirmed non-vacuous by sabotage (restoring the old check order): the TM diverges (`HitCap`)
    // and native/asm fault — see `three_way_oracle.rs`'s matching comment for the measured failure
    // this reorder closes.
    "fn nil(x) { x + 5 } fn ap(g, x) { g(x) } ap(nil, 0)",
    // A user `fn nil` called by name ONLY (never itself used as a value) sharing a program with an
    // unrelated CLOSED function-value (`add1`, passed to `ap`). Before the `$nil` alias, `add1`'s
    // closed closure was built as `cons(tag, nil)` — a bare `nil` that `lower_asm`'s
    // `reject_fn_value` then flagged as a value-use of the user's KEPT `fn nil`, rejecting the whole
    // program on every lowering backend even though `nil` itself is never value-used anywhere.
    // Confirmed non-vacuous by sabotage (reverting `$nil` at that one synthesis site): all three
    // lowering backends `Unsupported { "\`nil\` used as a value" }`, while reference and λ still
    // agree at 5. 2 + 3 = 5.
    "fn nil(x) { x + 1 } fn ap(g, x) { g(x) } fn add1(y) { y + 1 } nil(1) + ap(add1, 2)",
    // A user `fn cons` shadowing the list builtin — the `cons`-shaped twin of the `head`/`tail` pair
    // above, closing the one member a review found missing (reverting the `cons` helper to its bare
    // name left both oracle suites green). `defunc` builds every closure as `$cons(tag, env)`, so a
    // bare `cons` here would let this user function capture the closure representation itself —
    // `add1`'s closed closure would become `(tag + env)` (the user's `cons` computes `a + b`, not a
    // pair), and the dispatcher's `$head($clos)` tag test then reads that number as a list. Confirmed
    // non-vacuous by sabotage (reverting the `cons` helper's `"$cons"` to the bare `"cons"`):
    // reference/λ still agree at 10, the TM diverges (`HitCap`), and native faults
    // (`Fault("head of empty list")`). 3 + 7 = 10.
    "fn cons(a, b) { a + b } fn ap2(g, a, b) { g(a, b) } cons(1, 2) + ap2(cons, 3, 4)",
];

/// Programs that only TM/native can run three-way with the reference — the λ backend v1 REJECTS them
/// (`LowerError`) since they involve mutable-in-closure capture or a `fn` inside a mutation region.
/// Since native shares `lower_asm`/`defunc` with the TM, these still exercise `native == asm-interp`
/// (the boxing/mutable-capture codegen path), just without the λ leg.
const LAMBDA_LIMITATION_DEMOS: &[&str] = &[
    "let mut x = 1; x = x + 1; let x = x + 10; x",
    "let mut acc = 0; fn bump(n) { n + 1 } acc = bump(acc); acc = bump(acc); acc",
    "let mut n = 1; fn apply0(g) { g(0) } let f = |x| x + n; n = 10; apply0(f)",
    "let mut c = 0; fn twice(g) { g(0); g(0); } let bump = |x| { c = c + 1; c }; twice(bump); c",
];

/// Values that exceed `MAX_FIELD_WIDTH` (64) UNARY cells — the unary tape cannot represent them (every
/// value here is « 2⁶⁴, so the TM's `Binary` encoding represents all of them fine; this demo set is a
/// unary-vs-native contrast, not a TM-backend-vs-native one — Task 17's correction to this file). Native
/// compiles to real 64-bit registers, so it has no such ceiling at any encoding; this is native's
/// distinctive leg.
const BEYOND_FIELD_WIDTH_DEMOS: &[&str] = &[
    "100 * 100",
    "let n = 500; n + n",
    "fn sum(n) { if n == 0 { 0 } else { n + sum(n - 1) } } sum(100)",
    "[100, 200, 300]",
];

/// Values at or past 2⁶⁴ — the gap `past_the_u64_ceiling_the_backends_diverge_by_design` below
/// exercises; before that test existed, nothing did.
///
/// IT CANNOT BE AN AGREEMENT TEST, and this must not be "fixed" into one. The backends diverge here BY
/// DESIGN: the reference and native SATURATE (`tm/asm.rs`'s `saturating_add`/`saturating_mul`), while
/// the TM halts in its rule-less overflow guard (`tm/lower_tm.rs`'s `Builder::overflow`) and never
/// saturates at any width up to the 64-cell ceiling. Both behaviours are deliberate; they are simply
/// different, and nothing recorded that in an executable form before this test.
///
/// Measured 2026-07-29: each of these gives reference `Nat(u64::MAX)`, native `Nat(u64::MAX)`, binary
/// TM `Overflow` (having widened to 64), unary TM `Overflow`. The 20-digit literal parses with zero
/// diagnostics, so these need no special construction.
const SATURATION_DEMOS: &[&str] =
    &["18446744073709551615 + 1", "let n = 18446744073709551615; n + 1", "4294967295 * 4294967295 * 4294967295"];

/// Runtime-faulting programs: the reference faults (`RunError::Runtime`) and native reports a
/// `NativeRun::Fault` — the shared "no value, but not a crash and not a cap" outcome.
const FAULT_DEMOS: &[&str] = &["head(nil)", "tail(nil)"];

/// Emits one `#[test]` per encoding — each running the WHOLE first-order suite under that encoding —
/// and records what it emitted into `EMITTED` so the coverage guard below can compare against
/// `encodings()` instead of a second hard-coded copy of it.
///
/// The axis is per-encoding rather than per-demo because the runner (cargo-nextest) schedules every
/// test from every binary in one parallel pool: two encoding tests run concurrently, so adding the
/// binary leg costs roughly nothing in wall-clock, whereas one test doing both legs would have made
/// this file's single long pole twice as long.
macro_rules! four_way_tests {
    ($( $test:ident => $enc:expr ),* $(,)?) => {
        $(
            #[test]
            fn $test() {
                let kind = encoding_named($enc);
                for src in FIRST_ORDER_DEMOS {
                    assert_four_way(src, kind);
                }
            }
        )*

        /// Every encoding name the macro above actually emitted a test for.
        const EMITTED: &[&str] = &[ $( $enc ),* ];
    };
}

four_way_tests! {
    four_way_oracle_on_the_first_order_suite_unary => "unary",
    four_way_oracle_on_the_first_order_suite_binary => "binary",
}

/// The hazard this guards: the macro invocation above (`four_way_tests!`) hard-codes which encodings
/// get a test, while `encodings()` now DERIVES from `EncodingKind::ALL` and so tracks the enum by
/// itself. Add a row to `encoding_kinds!` in `tm/header.rs` and — once past the compile error
/// `tm_leg`'s wildcard-free match raises, which is what drags a developer into this file in the first
/// place — the new encoding would, without this guard, be covered by NOTHING while every remaining test
/// still passes: the file gets faster and weaker at the same time, because nothing forces the
/// `four_way_tests!` invocation itself to grow a matching arm.
/// Deleting a generated test has the identical signature.
///
/// So: derive the expectation from `encodings()` AT RUNTIME and compare against `EMITTED`. Never
/// hard-code the expected answer a second time, or this guard just restates the thing it checks.
///
/// What this does NOT catch: whether any generated test's BODY is correct. It proves only that every
/// encoding is covered by SOME test; `assert_four_way` carries the actual assertions.
#[test]
fn every_encoding_has_a_four_way_test() {
    let mut expected: Vec<&str> = encodings().into_iter().map(|(name, _)| name).collect();
    let mut emitted: Vec<&str> = EMITTED.to_vec();
    expected.sort_unstable();
    emitted.sort_unstable();
    assert_eq!(
        emitted, expected,
        "the tests `four_way_tests!` emits do not match `encodings()`; an encoding was added or \
         removed, or a generated test was deleted, without updating the macro invocation"
    );
}

#[test]
fn native_matches_asm_interp_on_the_first_order_suite() {
    for src in FIRST_ORDER_DEMOS {
        assert_native_matches_asm(src);
    }
}

#[test]
fn native_matches_asm_interp_on_lambda_limitation_demos() {
    // λ refuses these; native (sharing `lower_asm`/`defunc` with the TM) still runs them and must
    // agree with the asm interpreter — this is the mutable-capture / boxing codegen path.
    for src in LAMBDA_LIMITATION_DEMOS {
        assert_native_matches_asm(src);
    }
}

/// NOT deleted by Task 17 (`tm-binary-encoding`), even though the encoding it contrasts against
/// (`Unary`) is no longer the TM backend's only option: this still tests a REAL difference, just a
/// smaller one than the doc comments used to claim. See `the_tm_reports_its_ceiling_on_the_same_demos`
/// immediately below for the (now unary-scoped) contrast, and the module doc's "PAST 2^64" paragraph for
/// the honest remaining gap — values `>= 2^64`, where the backends diverge by design rather than agree;
/// `past_the_u64_ceiling_the_backends_diverge_by_design` and `SATURATION_DEMOS` now exercise exactly
/// that, on the TM side, in this file.
#[test]
fn native_runs_beyond_field_width() {
    for src in BEYOND_FIELD_WIDTH_DEMOS {
        assert_native_matches_reference(src);
    }
}

/// The TM's half of what `BEYOND_FIELD_WIDTH_DEMOS` claims — which until the overflow guard existed was
/// only a comment, because the TM leg could not be run on these at all: it would have corrupted its
/// register bank and handed back a WRONG answer rather than refusing. Now the ceiling is an outcome the
/// caller can see, so "native has no such ceiling" is a contrast between two measured results instead of
/// a measured result and an assertion in prose.
///
/// SCOPED TO UNARY (Task 17 correction): this pins `Unary::default()` specifically, not "the TM
/// backend". Every value in `BEYOND_FIELD_WIDTH_DEMOS` is « 2⁶⁴, so re-running this loop with
/// `Binary::default()` in place of `Unary::default()` would NOT overflow — the binary TM would agree
/// with native and the reference on all four. That is exactly the trade the encoding toggle bought:
/// this test still demonstrates a real, measured gap, but it is "native vs. unary", and the gap
/// narrower than "native vs. the TM backend" would suggest — see `crates/redextape-core/src/tm.rs`'s
/// `TmRun::Overflow` doc and `docs/superpowers/specs/2026-07-26-tm-binary-encoding-design.md`.
#[test]
fn the_tm_reports_its_ceiling_on_the_same_demos() {
    for src in BEYOND_FIELD_WIDTH_DEMOS {
        let core = core_of(src);
        assert!(
            matches!(run_tm(&core, &Unary::default(), TM_DEFAULT_CAPS), TmRun::Overflow),
            "the TM must REPORT that it cannot represent this, not miscompile it: {src}"
        );
    }
}

/// The OTHER half of the Task-17 correction, as a measured result rather than a doc comment. Every
/// value in `BEYOND_FIELD_WIDTH_DEMOS` is « 2⁶⁴, so `Binary` represents all of them: it runs all four
/// and agrees with the reference (and so, transitively, with native — `native_runs_beyond_field_width`
/// above pins native against the same reference values).
///
/// Measured 2026-07-29: all four fit at width 16, including the heap list `[100, 200, 300]`.
///
/// Together with `the_tm_reports_its_ceiling_on_the_same_demos` (which MUST be kept — it is the
/// control), this establishes as two measured results what the module doc previously only asserted in
/// prose: the gap this file exhibits is "native vs. UNARY", not "native vs. the TM backend".
#[test]
fn binary_runs_the_demos_unary_cannot_represent() {
    for src in BEYOND_FIELD_WIDTH_DEMOS {
        let reference = run(src).unwrap_or_else(|e| panic!("reference run failed for `{src}`: {e:?}"));
        let core = core_of(src);
        let (tm, enc) = tm_leg(&core, EncodingKind::Binary);
        match tm {
            TmRun::Ran { tapes } => assert_eq!(
                decode_tape(&tapes, &reference, &*enc),
                Some(reference.clone()),
                "binary-TM vs reference disagree for: {src}"
            ),
            other => panic!("binary must RUN what unary cannot represent, got {other:?} for: {src}"),
        }
    }
}

/// Native's ceiling-free claim at the ONE place it is genuinely load-bearing, and the TM's refusal
/// beside it. See `SATURATION_DEMOS` for why agreement is impossible here by construction.
///
/// The TM half loops over `encodings()` rather than naming `Binary`: this is a claim about the TM
/// BACKEND, not about one encoding, so a third encoding must satisfy it too the day it is added.
#[test]
fn past_the_u64_ceiling_the_backends_diverge_by_design() {
    for src in SATURATION_DEMOS {
        let reference = run(src).unwrap_or_else(|e| panic!("reference run failed for `{src}`: {e:?}"));
        assert_eq!(reference, Value::Nat(u64::MAX), "these demos exist in order to saturate: {src}");
        let core = core_of(src);
        match run_native(&core, DEFAULT_CAPS) {
            NativeRun::Ran(outcome) => assert_eq!(
                decode_asm(&outcome, &reference),
                Some(reference.clone()),
                "native must saturate exactly as the reference does: {src}"
            ),
            other => panic!("native must run `{src}`, got {other:?}"),
        }
        for (name, kind) in encodings() {
            let (tm, _) = tm_leg(&core, kind);
            assert!(
                matches!(tm, TmRun::Overflow),
                "the {name} TM must REFUSE this, not saturate and not miscompile: {src} gave {tm:?}"
            );
        }
    }
}

#[test]
fn faults_diverge_on_native() {
    for src in FAULT_DEMOS {
        let reference = run(src);
        let core = core_of(src);
        match (reference, run_native(&core, DEFAULT_CAPS)) {
            (Err(RunError::Runtime(_)), NativeRun::Fault(_)) => {}
            (r, n) => panic!("expected reference Runtime + native Fault for {src}:\n  reference={r:?}\n  native={n:?}"),
        }
    }
}

/// A first-order expression generator whose value stays `< 8`-leaf-rooted arithmetic/comparison/if,
/// shape supplied by `redextape-test-support`'s `arb_expr_over`, shared with `redextape-core`'s
/// `arb_tm_safe_expr` in `three_way_oracle.rs` rather than reused from it. Unlike that generator native
/// has NO `MAX_FIELD_WIDTH` bound, so leaves are widened to `0..1000` — native compiles to real 64-bit
/// registers and never needs to stay under 64.
///
/// `arb_tm_mixed_range_expr` (below) is this generator's STRUCTURAL TWIN — same `prop_recursive(3, 8,
/// 3, ..)` parameters and operator set, a different leaf strategy. That was once a claim nothing
/// enforced, and a future edit to either could silently desync them. It is now ENFORCED: both call
/// `arb_expr_over` from `redextape-test-support`, so the shape exists once and the leaf is the only
/// thing either supplies. Changing the recursion parameters or the arm set is a single edit there that
/// necessarily reaches both — there is no longer a second copy to fall out of step.
fn arb_native_safe_expr() -> impl Strategy<Value = String> {
    arb_expr_over((0u64..1000).prop_map(|n| n.to_string()))
}

proptest! {
    #![proptest_config(ProptestConfig { cases: 64, ..ProptestConfig::default() })]

    /// Random wide-range (no `MAX_FIELD_WIDTH` bound) arithmetic/comparison/if programs: `native ==
    /// reference` AND `native == asm-interp`. The generator produces no loops/functions/faults, so a
    /// `HitCap`/`LowerError`/`Fault` would itself be a bug and trips the catch-all.
    #[test]
    fn native_agrees_with_reference_and_asm_on_random_programs(src in arb_native_safe_expr()) {
        let reference = run(&src);
        let (prog, ds) = parse(&src);
        prop_assume!(ds.is_empty()); // skip anything that does not parse/type-check
        let core = desugar(&prog.unwrap());
        let native = run_native(&core, DEFAULT_CAPS);
        match (reference, native) {
            (Ok(rv), NativeRun::Ran(outcome)) => {
                prop_assert_eq!(decode_asm(&outcome, &rv), Some(rv.clone()), "native vs reference disagree: {}", src);
                let lowered = lower_program(&core).expect("first-order arithmetic/if must lower to asm");
                match run_asm(&lowered, DEFAULT_CAPS) {
                    AsmRun::Ran(asm_outcome) => {
                        prop_assert_eq!(decode_asm(&asm_outcome, &rv), Some(rv), "native vs asm-interp disagree: {}", src);
                    }
                    other => prop_assert!(false, "asm-interp did not run {}: {:?}", src, other),
                }
            }
            (r, n) => prop_assert!(false, "native mismatch for {}:\n  reference={:?}\n  native={:?}", src, r, n),
        }
    }
}

/// Same shape as `arb_native_safe_expr` — both get it from `arb_expr_over`, whose own doc is the one
/// place the recursion parameters and arm set are written down. Restating them here would recreate, at
/// the doc layer, exactly the duplication that crate exists to remove: a copy that goes stale the day
/// the real parameters change in another crate.
///
/// What differs, and all this generator supplies, is a MIXED leaf: `prop_oneof!` over a small range
/// unary can represent (`0..8`, reused verbatim from
/// `redextape-core`'s `arb_tm_safe_expr` in `three_way_oracle.rs` — that generator uses these exact
/// recursion parameters and its doc comment records a measured max value of 27 over 2M samples, well
/// under the 64-cell ceiling) and the existing wide `0..1000` range, weighted 4:1 toward the small range.
///
/// `arb_native_safe_expr` itself is UNTOUCHED (`native_agrees_with_reference_and_asm_on_random_programs`
/// depends on its pure `0..1000` leaves); this is a separate generator for the TM-legs proptest only.
///
/// Do not read `0..8` as "sitting at 64 minus a little room" — it is nowhere near the ceiling. The
/// headroom is the point: `+` on two leaves can exceed a bound either leaf alone satisfies, so the small
/// range has to stay far enough below 64 that a handful of small leaves summed together (this
/// generator's recursion can sum several) still lands under it. `0..8` is the same range
/// `arb_tm_safe_expr` already proved safe under IDENTICAL recursion parameters, so reusing it verbatim
/// carries that proof over rather than re-deriving a new bound.
fn arb_tm_mixed_range_expr() -> impl Strategy<Value = String> {
    let small = 0u64..8;
    let wide = 0u64..1000;
    arb_expr_over(prop_oneof![4 => small, 1 => wide].prop_map(|n| n.to_string()))
}

proptest! {
    #![proptest_config(ProptestConfig { cases: 64, ..ProptestConfig::default() })]

    /// The TM legs over `arb_tm_mixed_range_expr` — and they are ASYMMETRIC BY NECESSITY, which is
    /// the whole reason this test has its own doc comment.
    ///
    /// THE NAME SAYS "AGREES" FOR BINARY AND "NEVER WRONG" FOR UNARY BECAUSE THOSE ARE DIFFERENT
    /// CLAIMS, not a stylistic choice: binary is asserted to decode equal to the reference on every
    /// case it runs, full agreement; unary is asserted only to never decode to a WRONG value when it
    /// runs, and is allowed to refuse (`Overflow`) instead. No improvement to unary's fire rate collapses
    /// that gap — "never wrong when it runs" stays strictly weaker than "agrees" no matter how often it
    /// runs — so the name states the asymmetric claim directly rather than relying on a reader to find
    /// it in the comment below.
    ///
    /// The generator mixes a small range unary can represent with the wide `0..1000` range a 64-cell
    /// UNARY field cannot. So:
    ///
    ///   * BINARY is a FULL leg: it must run, and decode equal to the reference.
    ///   * UNARY is asserted NEVER WRONG, which is strictly weaker: `Ran` must decode equal to the
    ///     reference; `Overflow` is permitted and still expected on a real fraction of cases (any leaf
    ///     drawn from the wide range, or an unlucky sum of small ones, can still overflow).
    ///
    /// DO NOT READ THE NAME AS SYMMETRIC. The unary half does not claim unary computes these programs.
    /// It claims unary never SILENTLY computes them wrongly — a `Ran` that decodes to the wrong value
    /// is caught, a refusal is not a failure. That is weaker than the binary leg and stronger than the
    /// nothing that was here before, and it is stated rather than left for a reader to infer from the
    /// code.
    ///
    /// MEASURED FIRE RATE (2026-07-29): with the old `arb_native_safe_expr` (pure `0..1000` leaves),
    /// unary's `Ran` branch fired on ~0.6% of cases (11 of 1920, over 30 independent 64-case runs, and
    /// silent on 21 of those 30 runs). Retargeted at `arb_tm_mixed_range_expr`, instrumented the same
    /// way (a temporary `eprintln!` on every `Ran`) and run 30 independent times (64 cases each, 1920
    /// cases total, no fixed seed): 1159 `Ran` hits (~60.4% of cases), firing on all 30 of the 30 runs
    /// (every run saw between 29 and 45 hits; none saw zero). So: the unary half now exercises its
    /// assertion on a clear majority of cases, on every run, rather than being live only in aggregate.
    #[test]
    fn binary_tm_agrees_while_unary_tm_is_never_wrong_on_random_programs(src in arb_tm_mixed_range_expr()) {
        let reference = run(&src);
        prop_assume!(reference.is_ok());
        let rv = reference.unwrap();
        let (prog, ds) = parse(&src);
        prop_assume!(ds.is_empty());
        let core = desugar(&prog.unwrap());

        let (btm, benc) = tm_leg(&core, EncodingKind::Binary);
        match btm {
            TmRun::Ran { tapes } => prop_assert_eq!(
                decode_tape(&tapes, &rv, &*benc),
                Some(rv.clone()),
                "binary-TM vs reference disagree: {}",
                src
            ),
            other => prop_assert!(false, "binary must run {}: {:?}", src, other),
        }

        // The weaker half. A refusal is fine; a WRONG ANSWER is not.
        let (utm, uenc) = tm_leg(&core, EncodingKind::Unary);
        if let TmRun::Ran { tapes } = utm {
            prop_assert_eq!(
                decode_tape(&tapes, &rv, &*uenc),
                Some(rv.clone()),
                "unary-TM RAN and produced the WRONG answer: {}",
                src
            );
        }
    }
}

/// The 60.4% figure in `binary_tm_agrees_while_unary_tm_is_never_wrong_on_random_programs`'s doc is
/// LOAD-BEARING: it is the whole reason that test's unary half is not near-vacuous. Before the mixed
/// generator it was 0.6%, and the check asserted nothing on ~70% of runs.
///
/// Nothing used to fail if a leaf-range or weight edit walked that back — the doc comment would simply
/// become false. This pins a FLOOR, deterministically (fixed RNG, so it cannot flake), well below the
/// measured value: the point is to catch a regression to near-zero, not to pin 60.4% exactly, which
/// would break on any legitimate retuning.
#[test]
fn the_unary_leg_of_the_random_test_actually_fires() {
    use proptest::strategy::{Strategy, ValueTree};
    use proptest::test_runner::{Config, RngAlgorithm, TestRng, TestRunner};

    const SAMPLES: usize = 200;
    // 30% of SAMPLES. TWO measurements, deliberately distinguished because they come from different
    // sampling and a reader should not have to guess which this floor is set against: the neighbouring
    // proptest's doc records ~60.4% (1920 cases across 30 RANDOMISED runs), while THIS test's own
    // fixed-seed run measures 126/200 = 63.0%. The floor sits far below both and far above the 1/200
    // (0.5%) the sabotage produces, so it discriminates the two regimes under either figure.
    const FLOOR: usize = 60;

    let mut runner = TestRunner::new_with_rng(Config::default(), TestRng::deterministic_rng(RngAlgorithm::ChaCha));
    let strat = arb_tm_mixed_range_expr();
    let mut ran = 0usize;
    for _ in 0..SAMPLES {
        let src = strat.new_tree(&mut runner).expect("generator produces a value").current();
        let core = core_of(&src);
        if matches!(tm_leg(&core, EncodingKind::Unary).0, TmRun::Ran { .. }) {
            ran += 1;
        }
    }
    assert!(
        ran >= FLOOR,
        "the unary leg ran on only {ran}/{SAMPLES} generated programs (floor {FLOOR}); the mixed-range \
         generator's small-leaf weight was probably reduced, which would make the ~60.4% figure in \
         `binary_tm_agrees_while_unary_tm_is_never_wrong_on_random_programs`'s doc comment false"
    );
}
