//! λ's grammar: its generated parser, its highlight queries, its capture table, and the thin wrapper
//! over `analysis::print_lambda_mapped` that makes it λ's authority.
//!
//! Model this on `mini.rs` — it went through review and this follows its shape — but read the module
//! doc there too: `@variable.parameter` is `Ident` in the mini-language and `Binder` here, and that
//! is why the tables are per-grammar rather than shared. Design §5.1.

use crate::grammar::{Grammar, compare_classified};
use redextape_core::Span;
use redextape_core::analysis::TokenClass;
use tree_sitter_language::LanguageFn;

unsafe extern "C" {
    fn tree_sitter_redextape_lambda() -> *const ();
}

/// Hand-written corpus. Every entry parses cleanly under the grammar and, between them, they reach
/// every position `queries/highlights.scm` names: a bare identifier as the whole `source_file`, both
/// sides of an application, an identifier inside a parenthesized term, an abstraction's body, and an
/// abstraction used as an application's argument (a shape `grammar.js` was widened to accept). Several
/// are lifted straight from `grammars/tree-sitter-redextape-lambda/test/corpus/terms.txt`, which
/// `tree-sitter test` already holds to the grammar, so reusing them costs nothing new to trust.
pub const CORPUS: &[(&str, &str)] = &[
    ("empty", ""),
    ("bare identifier", "x"),
    ("application is left-associative", "f x y"),
    ("a binder body extends as far right as it can", "λx. f x"),
    ("the backslash alias parses identically", "\\x. x"),
    ("parentheses, and a compiler-generated $ name", "(λ$store. $store) (λa.λb. a)"),
    ("a bare abstraction is legal in argument position", "f λx. x"),
    ("an abstraction argument's own body still extends as far right as it can", "λx. x λy. y"),
    ("the pinned printed term", "λx. (x x)"),
    // `print_lambda_mapped` can never write this shape — `parens` is reached only for an `Abs` in
    // function position and for a non-`Var` atom, and `(x)` is neither — but an editor's user can
    // still type it, and `(parenthesized_term (identifier) @variable)` is the only pattern in
    // `queries/highlights.scm` that fires on an identifier as `parenthesized_term`'s DIRECT child.
    // Without this entry that pattern has zero coverage anywhere in the pipeline, and
    // `tests/lambda.rs`'s `every_lambda_query_pattern_fires_over_the_corpus` exists to catch its
    // absence.
    ("a parenthesized variable", "f (x)"),
];

/// λ's highlight queries, compiled into the binary so the test needs no file I/O and cannot read a
/// stale copy out of a build directory.
pub const HIGHLIGHTS: &str = include_str!("../../../grammars/tree-sitter-redextape-lambda/queries/highlights.scm");

/// Where the two vocabularies meet, FOR λ. The mini-language gets its own table in `mini.rs`; design
/// §5.1 records why one shared table was wrong — `@variable.parameter` is `Binder` here, where
/// `print_lambda_mapped` folds the bound name into the binder's own span, and `Ident` in the
/// mini-language, where `class_of` calls a parameter an identifier. Both are right for their own
/// language.
///
/// Standard tree-sitter capture names on the left, because editors' themes are written against them;
/// `TokenClass` on the right, because that is what `print_lambda_mapped` produces. Total over every
/// capture the queries emit (`the_capture_map_is_total_over_the_queries`), and carries no row no
/// query uses (`every_map_row_is_used_by_a_query`) — see `tests/lambda.rs`.
pub const CAPTURE_CLASSES: &[(&str, TokenClass)] = &[
    ("keyword.function", TokenClass::Binder),
    ("variable.parameter", TokenClass::Binder),
    ("variable", TokenClass::Ident),
    ("punctuation.delimiter", TokenClass::Punct),
    ("punctuation.bracket", TokenClass::Punct),
];

/// λ's grammar: its generated parser, its highlight queries and its capture table together as one
/// `Grammar` value.
///
/// See `mini::MINI`'s doc comment for why `LanguageFn::from_raw` over the generated symbol, rather
/// than a hand-rolled transmute, is the sanctioned conversion — the same reasoning applies here
/// unchanged.
pub static LAMBDA: Grammar = Grammar {
    name: "lambda",
    // SAFETY: `tree_sitter_redextape_lambda` is generated by `tree-sitter generate` and returns a
    // pointer to a `'static` `TSLanguage`, which is exactly what `LanguageFn::from_raw` requires. The
    // ABI it was generated at is pinned to 15 and checked by `abi_version_is_pinned` below, so a
    // toolchain bump that changes it fails here by name rather than as an opaque `set_language` error.
    language_fn: unsafe { LanguageFn::from_raw(tree_sitter_redextape_lambda) },
    highlights: HIGHLIGHTS,
    capture_classes: CAPTURE_CLASSES,
};

/// Lower a mini-language program to a λ term and print it with its classification, or `None` when the
/// program does not lower.
///
/// **THE CORPUS THIS FEEDS IS PRODUCED, NOT AUTHORED** — design §4's central asymmetry. The
/// mini-language has `analysis::classify_source`, a function FROM TEXT TO SPANS, so its differential
/// can classify any string a human writes. λ has no such function: its only authority is
/// `print_lambda_mapped`, which PRODUCES text and spans TOGETHER rather than accepting either
/// independently. So a λ corpus entry cannot be hand-typed and then classified — it has to come out of
/// this pipeline: `parser::parse` -> `desugar::desugar` -> `lambda::lower` -> `print_lambda_mapped`.
///
/// **THIS MUST NOT REDUCE**, and never will: the pipeline stops at `lower`, which produces a
/// `LambdaTerm`, and `print_lambda_mapped`, which prints one. Neither calls a reducer. A λ measurement
/// that reduces has previously cost this machine 60 GiB of RAM and all of swap — see the roadmap.
///
/// **Lowering is allowed to fail, and that is not this function's failure to report** — `lower` returns
/// `Result` because `LowerError::StatefulClosure`/`Unsupported`/`TooDeep` are real, expected outcomes
/// for some mini-language programs, not defects. Callers filter on `None`; they must not treat it as an
/// error. `None` also covers a source that fails to parse, since an unparseable program has nothing to
/// desugar.
///
/// Every step here is fallible and returns `None` rather than panicking: this is library code under
/// `src/`, where `clippy.toml`'s `unwrap`/`expect`/`panic` exemption does not reach.
#[must_use]
pub fn printed_term(src: &str) -> Option<(String, Vec<(Span, TokenClass)>)> {
    let (program, _diagnostics) = redextape_core::parser::parse(src);
    let program = program?;
    let core = redextape_core::desugar::desugar(&program);
    let term = redextape_core::lambda::lower(&core).ok()?;
    Some(redextape_core::lambda::print_lambda_mapped(&term))
}

/// Compare the λ grammar's projected captures against `print_lambda_mapped`'s own classification of
/// the same printed text.
///
/// **THE DIRECTION MATTERS**, the same as `mini::compare`: `print_lambda_mapped` is the authority here
/// because it is the only function that can classify λ text at all, not because it was chosen over some
/// alternative. A divergence is always a defect in `grammar.js` or `highlights.scm`, never a reason to
/// relax the comparison.
///
/// # Errors
///
/// As `compare_classified`, run with λ's shipped `HIGHLIGHTS`.
pub fn compare_printed(text: &str, want: &[(Span, TokenClass)]) -> Result<(), String> {
    compare_classified(&LAMBDA, HIGHLIGHTS, text, want)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A toolchain bump that changes the generated ABI past what the Rust crate reads presents as a
    /// bare `set_language` failure, which reads like a build error rather than a version error.
    /// Pinning it here makes the message name the real cause.
    #[test]
    fn abi_version_is_pinned() {
        assert_eq!(
            LAMBDA.language().abi_version(),
            15,
            "regenerate with the pinned tree-sitter CLI 0.25.10; ABI 14 means tree-sitter.json was not picked up"
        );
    }
}
