//! Holds the tree-sitter grammars to the hand-written front end.
//!
//! **A TEST-ONLY CRATE, and that is why it is a crate.** The natural home for this would be a module
//! inside `redextape-core`, but that would put `tree-sitter` and a C `build-dependency` in the
//! manifest of the crate whose whole identity is being WASM-clean. `redextape-test-support` exists
//! for the same reason and states it the same way.
//!
//! **NOTHING HERE MAY LOWER A CST.** The roadmap's tree-sitter entry permits a highlighting-only
//! lane and forbids a second authoritative grammar; its test for "authoritative" is lowering. A
//! tree-sitter node reaching a `redextape_core` AST type is the line this crate must not cross.

use redextape_core::Span;
use redextape_core::analysis::TokenClass;
use tree_sitter::{Parser, Query, QueryCursor, StreamingIterator, Tree};
use tree_sitter_language::LanguageFn;

unsafe extern "C" {
    fn tree_sitter_redextape() -> *const ();
}

/// The mini-language grammar, loaded from the generated parser this crate compiles.
///
/// Built through `tree_sitter_language::LanguageFn`, the same constructor every generated
/// `bindings/rust/lib.rs` uses (see e.g. `tree-sitter-bash`), rather than `std::mem::transmute`ing
/// the raw symbol into a `tree_sitter::Language` by hand: it is the crate's own sanctioned API for
/// this exact conversion, so the unsafety is confined to the one line `tree-sitter` itself asks
/// callers to justify, not spread across a transmute this crate would have to keep proving is
/// layout-compatible on every `tree-sitter` upgrade.
#[must_use]
pub fn language() -> tree_sitter::Language {
    // SAFETY: `tree_sitter_redextape` is generated by `tree-sitter generate` and returns a pointer
    // to a `'static` `TSLanguage`, which is exactly what `LanguageFn::from_raw` requires. The ABI it
    // was generated at is pinned to 15 and checked by `abi_version_is_pinned` below, so a toolchain
    // bump that changes it fails here by name rather than as an opaque `set_language` error.
    let f = unsafe { LanguageFn::from_raw(tree_sitter_redextape) };
    f.into()
}

/// Parse mini-language source.
///
/// # Errors
///
/// Returns a message in two cases. One: the generated parser's ABI is incompatible with the linked
/// `tree-sitter` crate — the failure a toolchain bump produces, and why this returns `Result` rather
/// than panicking, since a bare abort here reads like a build problem rather than a version problem.
/// Two: tree-sitter returns no tree, which it does only under a timeout or cancellation, and neither
/// is set here. **A syntax error is neither of these.** Source that does not lex or parse cleanly
/// still produces a `Tree`, just one containing `ERROR`/`MISSING` nodes — see `error_nodes`.
pub fn parse(src: &str) -> Result<Tree, String> {
    let mut p = Parser::new();
    p.set_language(&language())
        .map_err(|e| format!("the generated parser's ABI is incompatible with the linked tree-sitter crate: {e}"))?;
    p.parse(src, None).ok_or_else(|| {
        "tree-sitter produced no tree; it returns None only under a timeout or cancellation, and neither is set"
            .to_string()
    })
}

/// Byte ranges of every `ERROR` and `MISSING` node, in offset order.
///
/// A corpus entry that fails to parse would otherwise yield an empty capture list and compare equal
/// to nothing, so the differential checks this first rather than separately.
#[must_use]
pub fn error_nodes(tree: &Tree) -> Vec<Span> {
    let mut out = Vec::new();
    let mut cursor = tree.walk();
    let mut stack = vec![tree.root_node()];
    while let Some(node) = stack.pop() {
        if node.is_error() || node.is_missing() {
            out.push(Span::new(node.start_byte(), node.end_byte()));
        }
        stack.extend(node.children(&mut cursor));
    }
    out.sort_by_key(|s| s.start);
    out
}

/// Hand-written corpus. Covers what `arb_expr_over` cannot reach: `fn`, `while`, closures, UFCS
/// chains, list literals, comments, and `mut`.
pub const CORPUS: &[(&str, &str)] = &[
    ("empty", ""),
    ("tail expression only", "1 + 2 * 3"),
    ("comparison and booleans", "if 1 == 1 { true } else { false }"),
    ("let and mut", "let mut acc = 0;\nacc"),
    ("assignment", "let mut n = 3;\nn = n - 1;\nn"),
    ("function and call", "fn double(n) { n * 2 }\ndouble(21)"),
    ("while loop", "let mut n = 3;\nwhile n > 0 { n = n - 1; }\nn"),
    ("closure", "let add1 = |x| x + 1;\nadd1(1)"),
    ("closure with two parameters", "let add = |a, b| a + b;\nadd(1, 2)"),
    ("ufcs chain", "[3, 1, 2].map(|x| x + 1).fold(0, |a, b| a + b)"),
    ("trailing commas", "fn f(a, b,) { a + b }\nf(1, 2,)"),
    ("comments", "// leading\nlet x = 1; // trailing\nx + 1"),
    ("nested blocks", "let x = { let y = 1; y + 1 };\nx"),
];

/// The mini-language's highlight queries, compiled into the binary so the test needs no file I/O and
/// cannot read a stale copy out of a build directory.
pub const HIGHLIGHTS: &str = include_str!("../../../grammars/tree-sitter-redextape/queries/highlights.scm");

/// Where the two vocabularies meet, FOR THE MINI-LANGUAGE. λ and TM get their own tables when their
/// grammars land; design §5.1 records why one shared table was wrong — `@variable.parameter` is an
/// `Ident` here, where `class_of` calls a parameter an identifier, and a `Binder` in λ, where
/// `print_lambda_mapped` folds the bound name into the binder. Both are right for their own language.
///
/// Standard tree-sitter capture names on the left, because editors' themes are written against them;
/// `TokenClass` on the right, because that is what the hand-written front end produces. The table is
/// a function — `the_capture_map_has_no_duplicate_keys` pins that — total over every capture the
/// queries emit (`the_capture_map_is_total_over_the_queries`), and carries no row no query uses
/// (`every_map_row_is_used_by_a_query`).
///
/// The extra granularity on the left is DELIBERATELY UNCHECKED: `@function.call` and `@variable` both
/// project to `Ident`, so a grammar capturing every identifier as a call would pass the differential.
/// Design §6.1 prices the two alternatives and says why neither was taken.
pub const CAPTURE_CLASSES: &[(&str, TokenClass)] = &[
    ("keyword", TokenClass::Keyword),
    ("boolean", TokenClass::Bool),
    ("number", TokenClass::Nat),
    ("comment", TokenClass::Comment),
    ("operator", TokenClass::Operator),
    ("punctuation.bracket", TokenClass::Punct),
    ("punctuation.delimiter", TokenClass::Punct),
    ("function", TokenClass::Ident),
    ("function.call", TokenClass::Ident),
    ("variable", TokenClass::Ident),
    ("variable.parameter", TokenClass::Ident),
];

/// The class a capture name projects to, or `None` if the map does not cover it.
#[must_use]
pub fn class_for(capture: &str) -> Option<TokenClass> {
    CAPTURE_CLASSES.iter().find(|(n, _)| *n == capture).map(|(_, c)| *c)
}

/// Every capture name the queries actually use.
///
/// # Errors
///
/// Returns the compile error if `highlights.scm` is not a valid query for this grammar — which is
/// what a query naming a node the grammar no longer has produces.
pub fn query_capture_names() -> Result<Vec<String>, String> {
    let q = Query::new(&language(), HIGHLIGHTS).map_err(|e| format!("highlights.scm: {e}"))?;
    Ok(q.capture_names().iter().map(|n| (*n).to_string()).collect())
}

/// Run the highlight queries over `src` and project every capture through `CAPTURE_CLASSES`.
///
/// Returns offset-ordered `(Span, TokenClass)` with ONE ENTRY PER BYTE RANGE — the same shape and the
/// same unit as `analysis::classify_source`, which is what makes the comparison in
/// `tests/differential.rs` a direct equality rather than a reconciliation.
///
/// **Overlapping captures are collapsed, and disagreement is an `Err` rather than a choice.** The
/// broad `(identifier) @variable` pattern overlaps the role-specific ones by design; every identifier
/// role projects to `Ident`, so collapsing is sound. Two captures on one range projecting to
/// different classes means a query was written that this rule cannot resolve, and silently keeping
/// one of them would make the differential compare something nobody chose.
///
/// # Errors
///
/// Returns a message when the query fails to compile, when `parse` fails (its two cases, documented
/// there — NOT a syntax error: that yields `ERROR`/`MISSING` nodes from a tree `parse` still returns
/// successfully), when a capture has no row in `CAPTURE_CLASSES`, when two captures on one byte range
/// disagree, or when the query cursor hit its match limit — which would otherwise drop captures
/// silently and surface much later as an unexplained span-count mismatch in `compare`.
///
/// **THE DISAGREEMENT RULE COVERS IDENTICAL BYTE RANGES ONLY.** Every pattern the shipped queries use
/// captures a leaf, so two captures either land on the same range or on disjoint ones. A future
/// pattern capturing a composite node — `(call_expression) @function.call`, say — would produce an
/// entry OVERLAPPING several others without ever comparing unequal, and `compare` would then report a
/// span-count mismatch instead of naming the query. Capture leaves.
pub fn captures(src: &str) -> Result<Vec<(Span, TokenClass)>, String> {
    captures_with(HIGHLIGHTS, src)
}

/// `captures`, over a caller-supplied query.
///
/// **EXISTS SO THE DISAGREEMENT CHECK CAN BE SHOWN TO FIRE.** `a_conflicting_query_is_rejected` runs
/// a query that captures one identifier as two classes; without this entry point that error would be
/// unreachable from a test, and a check nobody has seen fail is a check nobody has tested.
///
/// # Errors
///
/// As `captures`.
pub fn captures_with(query_src: &str, src: &str) -> Result<Vec<(Span, TokenClass)>, String> {
    let lang = language();
    let q = Query::new(&lang, query_src).map_err(|e| format!("query failed to compile: {e}"))?;
    let names = q.capture_names().to_vec();
    let tree = parse(src)?;
    let mut cursor = QueryCursor::new();
    let mut by_span: std::collections::BTreeMap<(usize, usize), TokenClass> = std::collections::BTreeMap::new();
    let mut it = cursor.matches(&q, tree.root_node(), src.as_bytes());
    while let Some(m) = it.next() {
        for c in m.captures {
            let name = names[c.index as usize];
            let class = class_for(name).ok_or_else(|| format!("`@{name}` has no row in CAPTURE_CLASSES"))?;
            let key = (c.node.start_byte(), c.node.end_byte());
            if let Some(prev) = by_span.insert(key, class)
                && prev != class
            {
                // `get` rather than `&src[..]`: a slice that is not on a char boundary panics, and a
                // library path in this workspace may not panic. tree-sitter advances by codepoint so
                // the range should always be valid, but an error path is a poor place to find out.
                return Err(format!(
                    "two captures on {}..{} (`{}`) disagree: {prev:?} and {class:?} via `@{name}`",
                    key.0,
                    key.1,
                    src.get(key.0..key.1).unwrap_or("<not a char boundary>")
                ));
            }
        }
    }
    // DELIBERATELY UNTESTED. The default `QueryCursor` match limit is `u32::MAX` and this function
    // builds its own cursor rather than taking one, so reaching the limit here would take billions of
    // matches — not reachable from this crate's tests. Widening the public API to inject a cursor
    // purely to test this branch would trade a real API for a test of a branch that cannot fire in
    // practice, so it is left as it is: an arm that exists for the day the default changes or a
    // caller-supplied cursor is added, not one this suite can currently drive.
    if cursor.did_exceed_match_limit() {
        return Err("the query cursor hit its match limit, so captures were dropped".to_string());
    }
    Ok(by_span.into_iter().map(|((start, end), c)| (Span::new(start, end), c)).collect())
}

/// Compare the grammar's projected captures against the hand-written front end's classification.
///
/// **THE DIRECTION MATTERS.** `analysis::classify_source` is the authority; this function has no
/// opinion of its own. A divergence is always a defect in `grammar.js` or `highlights.scm`, never a
/// reason to relax the comparison.
///
/// Parse failure is checked FIRST. A source that produces `ERROR` nodes would otherwise yield a
/// short capture list, and a short list that happens to be a prefix of the truth is the shape of a
/// comparison that passes while covering nothing.
///
/// # Errors
///
/// Four distinct messages, and they are worth distinguishing because they mean different things:
///
/// - the grammar produced `ERROR`/`MISSING` nodes, so the source was never compared at all;
/// - a per-index divergence, naming the index, both texts and both classes;
/// - a length mismatch, naming which side produced more spans and the first extra one;
/// - anything `captures_with` itself reports — a query that will not compile, a capture with no row
///   in `CAPTURE_CLASSES`, two captures disagreeing on one range, or the match limit.
pub fn compare(src: &str) -> Result<(), String> {
    compare_with(HIGHLIGHTS, src)
}

/// `compare`, over a caller-supplied query.
///
/// **EXISTS SO THE COMPARISON CAN BE SHOWN TO FAIL.** `compare` delegating to this is the same shape
/// `captures` uses over `captures_with`, and for the same reason: without an entry point that takes a
/// query, neither of `compare`'s two failure blocks — the per-index mismatch loop and the
/// `want.len() != got.len()` extra-spans check — could be driven from a test, since the shipped
/// `HIGHLIGHTS` agrees with `classify_source` everywhere the corpus and the generated tests reach. A
/// check nobody has seen fail is a check nobody has tested.
///
/// # Errors
///
/// As `compare`.
pub fn compare_with(query_src: &str, src: &str) -> Result<(), String> {
    let tree = parse(src)?;
    let errors = error_nodes(&tree);
    if !errors.is_empty() {
        return Err(format!("the grammar produced ERROR/MISSING nodes at {errors:?}"));
    }

    let want = redextape_core::analysis::classify_source(src);
    let got = captures_with(query_src, src)?;

    for (i, (w, g)) in want.iter().zip(got.iter()).enumerate() {
        if w != g {
            // `get` rather than `&src[..]` throughout: a slice off a char boundary panics, and a
            // library path in this workspace may not panic. Same rule as `captures_with`.
            return Err(format!(
                "at index {i}: classify_source says {:?} {:?} at {}..{}, the grammar says {:?} {:?} at {}..{}",
                src.get(w.0.start..w.0.end).unwrap_or("<not a char boundary>"),
                w.1,
                w.0.start,
                w.0.end,
                src.get(g.0.start..g.0.end).unwrap_or("<not a char boundary>"),
                g.1,
                g.0.start,
                g.0.end,
            ));
        }
    }
    if want.len() != got.len() {
        let (longer, which) = if want.len() > got.len() { (&want, "classify_source") } else { (&got, "the grammar") };
        let extra = &longer[want.len().min(got.len())..];
        let first = extra.first().ok_or_else(|| {
            "unreachable: the lengths differ, so the longer side has at least one extra span".to_string()
        })?;
        return Err(format!(
            "{which} produced {} more span(s); the first is {:?} at {}..{}",
            extra.len(),
            src.get(first.0.start..first.0.end).unwrap_or("<not a char boundary>"),
            first.0.start,
            first.0.end,
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A toolchain bump that changes the generated ABI past what the Rust crate reads presents as a
    /// bare `set_language` failure, which reads like a build error rather than a version error.
    /// Pinning it here makes the message name the real cause.
    #[test]
    fn abi_version_is_pinned() {
        assert_eq!(
            language().abi_version(),
            15,
            "regenerate with the pinned tree-sitter CLI 0.26.12; ABI 14 means tree-sitter.json was not picked up"
        );
    }
}
