//! The mini-language's grammar: its generated parser, its highlight queries, its capture table, and
//! the thin wrappers over `analysis::classify_source` that make it the mini-language's authority.

use crate::grammar::{Grammar, compare_classified};
use redextape_core::analysis::TokenClass;
use tree_sitter_language::LanguageFn;

unsafe extern "C" {
    fn tree_sitter_redextape() -> *const ();
}

/// Hand-written corpus. Covers what `arb_expr_over` cannot reach: `fn`, `while`, closures, UFCS
/// chains, list literals, comments, and `mut`.
pub const CORPUS: &[(&str, &str)] = &[
    ("empty", ""),
    ("tail expression only", "1 + 2 * 3"),
    ("comparison and booleans", "if 1 == 1 { true } else { false }"),
    ("let and mut", "let mut acc = 0;\nacc"),
    ("assignment", "let mut n = 3;\nn = n - 1;\nn"),
    ("function and call", "fn double(n) { n * 2 }\ndouble(21)"),
    ("while loop", "let mut n = 3;\nwhile n > 0 { n = n - 1; }\nn"),
    ("closure", "let add1 = |x| x + 1;\nadd1(1)"),
    ("closure with two parameters", "let add = |a, b| a + b;\nadd(1, 2)"),
    ("ufcs chain", "[3, 1, 2].map(|x| x + 1).fold(0, |a, b| a + b)"),
    ("trailing commas", "fn f(a, b,) { a + b }\nf(1, 2,)"),
    ("comments", "// leading\nlet x = 1; // trailing\nx + 1"),
    ("nested blocks", "let x = { let y = 1; y + 1 };\nx"),
];

/// The mini-language's highlight queries, compiled into the binary so the test needs no file I/O and
/// cannot read a stale copy out of a build directory.
pub const HIGHLIGHTS: &str = include_str!("../../../grammars/tree-sitter-redextape/queries/highlights.scm");

/// Where the two vocabularies meet, FOR THE MINI-LANGUAGE. λ has its own table in `lambda.rs` now
/// that its grammar has landed; TM will get one when its grammar lands. Design §5.1 records why one
/// shared table was wrong — `@variable.parameter` is an
/// `Ident` here, where `class_of` calls a parameter an identifier, and a `Binder` in λ, where
/// `print_lambda_mapped` folds the bound name into the binder. Both are right for their own language.
///
/// Standard tree-sitter capture names on the left, because editors' themes are written against them;
/// `TokenClass` on the right, because that is what the hand-written front end produces. The table is
/// a function — `the_capture_map_has_no_duplicate_keys` pins that — total over every capture the
/// queries emit (`the_capture_map_is_total_over_the_queries`), and carries no row no query uses
/// (`every_map_row_is_used_by_a_query`).
///
/// The extra granularity on the left is DELIBERATELY UNCHECKED: `@function.call` and `@variable` both
/// project to `Ident`, so a grammar capturing every identifier as a call would pass the differential.
/// Design §6.1 prices the two alternatives and says why neither was taken.
pub const CAPTURE_CLASSES: &[(&str, TokenClass)] = &[
    ("keyword", TokenClass::Keyword),
    ("boolean", TokenClass::Bool),
    ("number", TokenClass::Nat),
    ("comment", TokenClass::Comment),
    ("operator", TokenClass::Operator),
    ("punctuation.bracket", TokenClass::Punct),
    ("punctuation.delimiter", TokenClass::Punct),
    ("function", TokenClass::Ident),
    ("function.call", TokenClass::Ident),
    ("variable", TokenClass::Ident),
    ("variable.parameter", TokenClass::Ident),
];

/// The mini-language grammar: its generated parser, its highlight queries and its capture table
/// together as one `Grammar` value.
///
/// The parser is loaded from the generated parser this crate compiles, built through
/// `tree_sitter_language::LanguageFn`, the same constructor every generated `bindings/rust/lib.rs`
/// uses (see e.g. `tree-sitter-bash`), rather than `std::mem::transmute`ing the raw symbol into a
/// `tree_sitter::Language` by hand: it is the crate's own sanctioned API for this exact conversion, so
/// the unsafety is confined to the one line `tree-sitter` itself asks callers to justify, not spread
/// across a transmute this crate would have to keep proving is layout-compatible on every
/// `tree-sitter` upgrade.
pub static MINI: Grammar = Grammar {
    name: "mini",
    // SAFETY: `tree_sitter_redextape` is generated by `tree-sitter generate` and returns a pointer to
    // a `'static` `TSLanguage`, which is exactly what `LanguageFn::from_raw` requires. The ABI it was
    // generated at is pinned to 15 and checked by `abi_version_is_pinned` below, so a toolchain bump
    // that changes it fails here by name rather than as an opaque `set_language` error.
    language_fn: unsafe { LanguageFn::from_raw(tree_sitter_redextape) },
    highlights: HIGHLIGHTS,
    capture_classes: CAPTURE_CLASSES,
};

/// Compare the mini-language grammar's projected captures against the hand-written front end's
/// classification.
///
/// **THE DIRECTION MATTERS.** `analysis::classify_source` is the authority; this function has no
/// opinion of its own. A divergence is always a defect in `grammar.js` or `highlights.scm`, never a
/// reason to relax the comparison.
///
/// Parse failure is checked FIRST. A source that produces `ERROR` nodes would otherwise yield a
/// short capture list, and a short list that happens to be a prefix of the truth is the shape of a
/// comparison that passes while covering nothing.
///
/// # Errors
///
/// As `compare_classified`.
pub fn compare(src: &str) -> Result<(), String> {
    compare_with(HIGHLIGHTS, src)
}

/// `compare`, over a caller-supplied query.
///
/// **EXISTS SO THE COMPARISON CAN BE SHOWN TO FAIL.** `compare` delegating to this is the same shape
/// `captures` uses over `captures_with`, and for the same reason: without an entry point that takes a
/// query, neither of `compare_classified`'s two failure blocks — the per-index mismatch loop and the
/// `want.len() != got.len()` extra-spans check — could be driven from a test, since the shipped
/// `HIGHLIGHTS` agrees with `classify_source` everywhere the corpus and the generated tests reach. A
/// check nobody has seen fail is a check nobody has tested.
///
/// # Errors
///
/// As `compare`.
pub fn compare_with(query_src: &str, src: &str) -> Result<(), String> {
    let want = redextape_core::analysis::classify_source(src);
    compare_classified(&MINI, query_src, src, &want)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A toolchain bump that changes the generated ABI past what the Rust crate reads presents as a
    /// bare `set_language` failure, which reads like a build error rather than a version error.
    /// Pinning it here makes the message name the real cause.
    #[test]
    fn abi_version_is_pinned() {
        assert_eq!(
            MINI.language().abi_version(),
            15,
            "regenerate with the pinned tree-sitter CLI 0.25.10; ABI 14 means tree-sitter.json was not picked up"
        );
    }
}
