/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_result = 2,
  anon_sym_COLON = 3,
  anon_sym_ret = 4,
  anon_sym_halt = 5,
  anon_sym_nil = 6,
  anon_sym_mov = 7,
  anon_sym_head = 8,
  anon_sym_tail = 9,
  anon_sym_isempty = 10,
  anon_sym_box = 11,
  anon_sym_box_get = 12,
  anon_sym_box_set = 13,
  anon_sym_add = 14,
  anon_sym_sub = 15,
  anon_sym_mul = 16,
  anon_sym_cmpeq = 17,
  anon_sym_cmpne = 18,
  anon_sym_cmplt = 19,
  anon_sym_cmple = 20,
  anon_sym_cmpgt = 21,
  anon_sym_cmpge = 22,
  anon_sym_cons = 23,
  anon_sym_li = 24,
  anon_sym_jz = 25,
  anon_sym_jmp = 26,
  anon_sym_call = 27,
  anon_sym_COMMA = 28,
  sym_register = 29,
  sym_immediate = 30,
  sym_comment = 31,
  sym_source_file = 32,
  sym__line = 33,
  sym_result = 34,
  sym_label = 35,
  sym__label_name = 36,
  sym__instruction = 37,
  sym_nullary_instruction = 38,
  sym_reg_instruction = 39,
  sym_reg_reg_instruction = 40,
  sym_reg_reg_reg_instruction = 41,
  sym_imm_instruction = 42,
  sym_branch_instruction = 43,
  sym_jump_instruction = 44,
  aux_sym_source_file_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_result] = "result",
  [anon_sym_COLON] = ":",
  [anon_sym_ret] = "ret",
  [anon_sym_halt] = "halt",
  [anon_sym_nil] = "nil",
  [anon_sym_mov] = "mov",
  [anon_sym_head] = "head",
  [anon_sym_tail] = "tail",
  [anon_sym_isempty] = "isempty",
  [anon_sym_box] = "box",
  [anon_sym_box_get] = "box_get",
  [anon_sym_box_set] = "box_set",
  [anon_sym_add] = "add",
  [anon_sym_sub] = "sub",
  [anon_sym_mul] = "mul",
  [anon_sym_cmpeq] = "cmpeq",
  [anon_sym_cmpne] = "cmpne",
  [anon_sym_cmplt] = "cmplt",
  [anon_sym_cmple] = "cmple",
  [anon_sym_cmpgt] = "cmpgt",
  [anon_sym_cmpge] = "cmpge",
  [anon_sym_cons] = "cons",
  [anon_sym_li] = "li",
  [anon_sym_jz] = "jz",
  [anon_sym_jmp] = "jmp",
  [anon_sym_call] = "call",
  [anon_sym_COMMA] = ",",
  [sym_register] = "register",
  [sym_immediate] = "immediate",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_result] = "result",
  [sym_label] = "label",
  [sym__label_name] = "_label_name",
  [sym__instruction] = "_instruction",
  [sym_nullary_instruction] = "nullary_instruction",
  [sym_reg_instruction] = "reg_instruction",
  [sym_reg_reg_instruction] = "reg_reg_instruction",
  [sym_reg_reg_reg_instruction] = "reg_reg_reg_instruction",
  [sym_imm_instruction] = "imm_instruction",
  [sym_branch_instruction] = "branch_instruction",
  [sym_jump_instruction] = "jump_instruction",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_result] = anon_sym_result,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_ret] = anon_sym_ret,
  [anon_sym_halt] = anon_sym_halt,
  [anon_sym_nil] = anon_sym_nil,
  [anon_sym_mov] = anon_sym_mov,
  [anon_sym_head] = anon_sym_head,
  [anon_sym_tail] = anon_sym_tail,
  [anon_sym_isempty] = anon_sym_isempty,
  [anon_sym_box] = anon_sym_box,
  [anon_sym_box_get] = anon_sym_box_get,
  [anon_sym_box_set] = anon_sym_box_set,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_sub] = anon_sym_sub,
  [anon_sym_mul] = anon_sym_mul,
  [anon_sym_cmpeq] = anon_sym_cmpeq,
  [anon_sym_cmpne] = anon_sym_cmpne,
  [anon_sym_cmplt] = anon_sym_cmplt,
  [anon_sym_cmple] = anon_sym_cmple,
  [anon_sym_cmpgt] = anon_sym_cmpgt,
  [anon_sym_cmpge] = anon_sym_cmpge,
  [anon_sym_cons] = anon_sym_cons,
  [anon_sym_li] = anon_sym_li,
  [anon_sym_jz] = anon_sym_jz,
  [anon_sym_jmp] = anon_sym_jmp,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_register] = sym_register,
  [sym_immediate] = sym_immediate,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_result] = sym_result,
  [sym_label] = sym_label,
  [sym__label_name] = sym__label_name,
  [sym__instruction] = sym__instruction,
  [sym_nullary_instruction] = sym_nullary_instruction,
  [sym_reg_instruction] = sym_reg_instruction,
  [sym_reg_reg_instruction] = sym_reg_reg_instruction,
  [sym_reg_reg_reg_instruction] = sym_reg_reg_reg_instruction,
  [sym_imm_instruction] = sym_imm_instruction,
  [sym_branch_instruction] = sym_branch_instruction,
  [sym_jump_instruction] = sym_jump_instruction,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_result] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ret] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_halt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nil] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mov] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_head] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tail] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isempty] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_box] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_box_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_box_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mul] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cmpeq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cmpne] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cmplt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cmple] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cmpgt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cmpge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cons] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_li] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jz] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jmp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_immediate] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_result] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym__label_name] = {
    .visible = false,
    .named = true,
  },
  [sym__instruction] = {
    .visible = false,
    .named = true,
  },
  [sym_nullary_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_reg_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_reg_reg_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_reg_reg_reg_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_imm_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_branch_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_instruction] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_target = 2,
  field_type = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_target] = "target",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 1},
  [1] =
    {field_target, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_target, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == ',') ADVANCE(6);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_immediate);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(10);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_immediate);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'h', 4,
        'i', 5,
        'j', 6,
        'l', 7,
        'm', 8,
        'n', 9,
        'r', 10,
        's', 11,
        't', 12,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'd') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'm') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'm') ADVANCE(22);
      if (lookahead == 'z') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(25);
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'r') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_register);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == 'x') ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(41);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_jz);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_li);
      END_STATE();
    case 25:
      if (lookahead == 'v') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(45);
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_register);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      if (lookahead == 'b') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_box);
      if (lookahead == '_') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(51);
      if (lookahead == 'g') ADVANCE(52);
      if (lookahead == 'l') ADVANCE(53);
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(55);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 39:
      if (lookahead == 'd') ADVANCE(57);
      END_STATE();
    case 40:
      if (lookahead == 'm') ADVANCE(58);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_jmp);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_mov);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_mul);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_nil);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(59);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_ret);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_sub);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 49:
      if (lookahead == 'g') ADVANCE(61);
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 51:
      if (lookahead == 'q') ADVANCE(63);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(66);
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_cons);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_halt);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_head);
      END_STATE();
    case 58:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 59:
      if (lookahead == 'l') ADVANCE(70);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_tail);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_cmpeq);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_cmpge);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_cmpgt);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_cmple);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_cmplt);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_cmpne);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 73:
      if (lookahead == 'y') ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_result);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_box_get);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_box_set);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_isempty);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_result] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_ret] = ACTIONS(1),
    [anon_sym_halt] = ACTIONS(1),
    [anon_sym_nil] = ACTIONS(1),
    [anon_sym_mov] = ACTIONS(1),
    [anon_sym_head] = ACTIONS(1),
    [anon_sym_tail] = ACTIONS(1),
    [anon_sym_isempty] = ACTIONS(1),
    [anon_sym_box] = ACTIONS(1),
    [anon_sym_box_get] = ACTIONS(1),
    [anon_sym_box_set] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_sub] = ACTIONS(1),
    [anon_sym_mul] = ACTIONS(1),
    [anon_sym_cmpeq] = ACTIONS(1),
    [anon_sym_cmpne] = ACTIONS(1),
    [anon_sym_cmplt] = ACTIONS(1),
    [anon_sym_cmple] = ACTIONS(1),
    [anon_sym_cmpgt] = ACTIONS(1),
    [anon_sym_cmpge] = ACTIONS(1),
    [anon_sym_cons] = ACTIONS(1),
    [anon_sym_li] = ACTIONS(1),
    [anon_sym_jz] = ACTIONS(1),
    [anon_sym_jmp] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [sym_immediate] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym__line] = STATE(2),
    [sym_result] = STATE(2),
    [sym_label] = STATE(2),
    [sym__label_name] = STATE(21),
    [sym__instruction] = STATE(2),
    [sym_nullary_instruction] = STATE(2),
    [sym_reg_instruction] = STATE(2),
    [sym_reg_reg_instruction] = STATE(2),
    [sym_reg_reg_reg_instruction] = STATE(2),
    [sym_imm_instruction] = STATE(2),
    [sym_branch_instruction] = STATE(2),
    [sym_jump_instruction] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_result] = ACTIONS(9),
    [anon_sym_ret] = ACTIONS(11),
    [anon_sym_halt] = ACTIONS(11),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_mov] = ACTIONS(15),
    [anon_sym_head] = ACTIONS(15),
    [anon_sym_tail] = ACTIONS(15),
    [anon_sym_isempty] = ACTIONS(15),
    [anon_sym_box] = ACTIONS(15),
    [anon_sym_box_get] = ACTIONS(15),
    [anon_sym_box_set] = ACTIONS(15),
    [anon_sym_add] = ACTIONS(17),
    [anon_sym_sub] = ACTIONS(17),
    [anon_sym_mul] = ACTIONS(17),
    [anon_sym_cmpeq] = ACTIONS(17),
    [anon_sym_cmpne] = ACTIONS(17),
    [anon_sym_cmplt] = ACTIONS(17),
    [anon_sym_cmple] = ACTIONS(17),
    [anon_sym_cmpgt] = ACTIONS(17),
    [anon_sym_cmpge] = ACTIONS(17),
    [anon_sym_cons] = ACTIONS(17),
    [anon_sym_li] = ACTIONS(19),
    [anon_sym_jz] = ACTIONS(21),
    [anon_sym_jmp] = ACTIONS(23),
    [anon_sym_call] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym_result] = STATE(3),
    [sym_label] = STATE(3),
    [sym__label_name] = STATE(21),
    [sym__instruction] = STATE(3),
    [sym_nullary_instruction] = STATE(3),
    [sym_reg_instruction] = STATE(3),
    [sym_reg_reg_instruction] = STATE(3),
    [sym_reg_reg_reg_instruction] = STATE(3),
    [sym_imm_instruction] = STATE(3),
    [sym_branch_instruction] = STATE(3),
    [sym_jump_instruction] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_result] = ACTIONS(9),
    [anon_sym_ret] = ACTIONS(11),
    [anon_sym_halt] = ACTIONS(11),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_mov] = ACTIONS(15),
    [anon_sym_head] = ACTIONS(15),
    [anon_sym_tail] = ACTIONS(15),
    [anon_sym_isempty] = ACTIONS(15),
    [anon_sym_box] = ACTIONS(15),
    [anon_sym_box_get] = ACTIONS(15),
    [anon_sym_box_set] = ACTIONS(15),
    [anon_sym_add] = ACTIONS(17),
    [anon_sym_sub] = ACTIONS(17),
    [anon_sym_mul] = ACTIONS(17),
    [anon_sym_cmpeq] = ACTIONS(17),
    [anon_sym_cmpne] = ACTIONS(17),
    [anon_sym_cmplt] = ACTIONS(17),
    [anon_sym_cmple] = ACTIONS(17),
    [anon_sym_cmpgt] = ACTIONS(17),
    [anon_sym_cmpge] = ACTIONS(17),
    [anon_sym_cons] = ACTIONS(17),
    [anon_sym_li] = ACTIONS(19),
    [anon_sym_jz] = ACTIONS(21),
    [anon_sym_jmp] = ACTIONS(23),
    [anon_sym_call] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym_result] = STATE(3),
    [sym_label] = STATE(3),
    [sym__label_name] = STATE(21),
    [sym__instruction] = STATE(3),
    [sym_nullary_instruction] = STATE(3),
    [sym_reg_instruction] = STATE(3),
    [sym_reg_reg_instruction] = STATE(3),
    [sym_reg_reg_reg_instruction] = STATE(3),
    [sym_imm_instruction] = STATE(3),
    [sym_branch_instruction] = STATE(3),
    [sym_jump_instruction] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_result] = ACTIONS(32),
    [anon_sym_ret] = ACTIONS(35),
    [anon_sym_halt] = ACTIONS(35),
    [anon_sym_nil] = ACTIONS(38),
    [anon_sym_mov] = ACTIONS(41),
    [anon_sym_head] = ACTIONS(41),
    [anon_sym_tail] = ACTIONS(41),
    [anon_sym_isempty] = ACTIONS(41),
    [anon_sym_box] = ACTIONS(41),
    [anon_sym_box_get] = ACTIONS(41),
    [anon_sym_box_set] = ACTIONS(41),
    [anon_sym_add] = ACTIONS(44),
    [anon_sym_sub] = ACTIONS(44),
    [anon_sym_mul] = ACTIONS(44),
    [anon_sym_cmpeq] = ACTIONS(44),
    [anon_sym_cmpne] = ACTIONS(44),
    [anon_sym_cmplt] = ACTIONS(44),
    [anon_sym_cmple] = ACTIONS(44),
    [anon_sym_cmpgt] = ACTIONS(44),
    [anon_sym_cmpge] = ACTIONS(44),
    [anon_sym_cons] = ACTIONS(44),
    [anon_sym_li] = ACTIONS(47),
    [anon_sym_jz] = ACTIONS(50),
    [anon_sym_jmp] = ACTIONS(53),
    [anon_sym_call] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_identifier] = ACTIONS(58),
    [anon_sym_result] = ACTIONS(58),
    [anon_sym_COLON] = ACTIONS(60),
    [anon_sym_ret] = ACTIONS(58),
    [anon_sym_halt] = ACTIONS(58),
    [anon_sym_nil] = ACTIONS(58),
    [anon_sym_mov] = ACTIONS(58),
    [anon_sym_head] = ACTIONS(58),
    [anon_sym_tail] = ACTIONS(58),
    [anon_sym_isempty] = ACTIONS(58),
    [anon_sym_box] = ACTIONS(58),
    [anon_sym_box_get] = ACTIONS(58),
    [anon_sym_box_set] = ACTIONS(58),
    [anon_sym_add] = ACTIONS(58),
    [anon_sym_sub] = ACTIONS(58),
    [anon_sym_mul] = ACTIONS(58),
    [anon_sym_cmpeq] = ACTIONS(58),
    [anon_sym_cmpne] = ACTIONS(58),
    [anon_sym_cmplt] = ACTIONS(58),
    [anon_sym_cmple] = ACTIONS(58),
    [anon_sym_cmpgt] = ACTIONS(58),
    [anon_sym_cmpge] = ACTIONS(58),
    [anon_sym_cons] = ACTIONS(58),
    [anon_sym_li] = ACTIONS(58),
    [anon_sym_jz] = ACTIONS(58),
    [anon_sym_jmp] = ACTIONS(58),
    [anon_sym_call] = ACTIONS(58),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(62),
    [sym_identifier] = ACTIONS(64),
    [anon_sym_result] = ACTIONS(64),
    [anon_sym_ret] = ACTIONS(64),
    [anon_sym_halt] = ACTIONS(64),
    [anon_sym_nil] = ACTIONS(64),
    [anon_sym_mov] = ACTIONS(64),
    [anon_sym_head] = ACTIONS(64),
    [anon_sym_tail] = ACTIONS(64),
    [anon_sym_isempty] = ACTIONS(64),
    [anon_sym_box] = ACTIONS(64),
    [anon_sym_box_get] = ACTIONS(64),
    [anon_sym_box_set] = ACTIONS(64),
    [anon_sym_add] = ACTIONS(64),
    [anon_sym_sub] = ACTIONS(64),
    [anon_sym_mul] = ACTIONS(64),
    [anon_sym_cmpeq] = ACTIONS(64),
    [anon_sym_cmpne] = ACTIONS(64),
    [anon_sym_cmplt] = ACTIONS(64),
    [anon_sym_cmple] = ACTIONS(64),
    [anon_sym_cmpgt] = ACTIONS(64),
    [anon_sym_cmpge] = ACTIONS(64),
    [anon_sym_cons] = ACTIONS(64),
    [anon_sym_li] = ACTIONS(64),
    [anon_sym_jz] = ACTIONS(64),
    [anon_sym_jmp] = ACTIONS(64),
    [anon_sym_call] = ACTIONS(64),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(66),
    [sym_identifier] = ACTIONS(68),
    [anon_sym_result] = ACTIONS(68),
    [anon_sym_ret] = ACTIONS(68),
    [anon_sym_halt] = ACTIONS(68),
    [anon_sym_nil] = ACTIONS(68),
    [anon_sym_mov] = ACTIONS(68),
    [anon_sym_head] = ACTIONS(68),
    [anon_sym_tail] = ACTIONS(68),
    [anon_sym_isempty] = ACTIONS(68),
    [anon_sym_box] = ACTIONS(68),
    [anon_sym_box_get] = ACTIONS(68),
    [anon_sym_box_set] = ACTIONS(68),
    [anon_sym_add] = ACTIONS(68),
    [anon_sym_sub] = ACTIONS(68),
    [anon_sym_mul] = ACTIONS(68),
    [anon_sym_cmpeq] = ACTIONS(68),
    [anon_sym_cmpne] = ACTIONS(68),
    [anon_sym_cmplt] = ACTIONS(68),
    [anon_sym_cmple] = ACTIONS(68),
    [anon_sym_cmpgt] = ACTIONS(68),
    [anon_sym_cmpge] = ACTIONS(68),
    [anon_sym_cons] = ACTIONS(68),
    [anon_sym_li] = ACTIONS(68),
    [anon_sym_jz] = ACTIONS(68),
    [anon_sym_jmp] = ACTIONS(68),
    [anon_sym_call] = ACTIONS(68),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(70),
    [sym_identifier] = ACTIONS(72),
    [anon_sym_result] = ACTIONS(72),
    [anon_sym_ret] = ACTIONS(72),
    [anon_sym_halt] = ACTIONS(72),
    [anon_sym_nil] = ACTIONS(72),
    [anon_sym_mov] = ACTIONS(72),
    [anon_sym_head] = ACTIONS(72),
    [anon_sym_tail] = ACTIONS(72),
    [anon_sym_isempty] = ACTIONS(72),
    [anon_sym_box] = ACTIONS(72),
    [anon_sym_box_get] = ACTIONS(72),
    [anon_sym_box_set] = ACTIONS(72),
    [anon_sym_add] = ACTIONS(72),
    [anon_sym_sub] = ACTIONS(72),
    [anon_sym_mul] = ACTIONS(72),
    [anon_sym_cmpeq] = ACTIONS(72),
    [anon_sym_cmpne] = ACTIONS(72),
    [anon_sym_cmplt] = ACTIONS(72),
    [anon_sym_cmple] = ACTIONS(72),
    [anon_sym_cmpgt] = ACTIONS(72),
    [anon_sym_cmpge] = ACTIONS(72),
    [anon_sym_cons] = ACTIONS(72),
    [anon_sym_li] = ACTIONS(72),
    [anon_sym_jz] = ACTIONS(72),
    [anon_sym_jmp] = ACTIONS(72),
    [anon_sym_call] = ACTIONS(72),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(74),
    [sym_identifier] = ACTIONS(76),
    [anon_sym_result] = ACTIONS(76),
    [anon_sym_ret] = ACTIONS(76),
    [anon_sym_halt] = ACTIONS(76),
    [anon_sym_nil] = ACTIONS(76),
    [anon_sym_mov] = ACTIONS(76),
    [anon_sym_head] = ACTIONS(76),
    [anon_sym_tail] = ACTIONS(76),
    [anon_sym_isempty] = ACTIONS(76),
    [anon_sym_box] = ACTIONS(76),
    [anon_sym_box_get] = ACTIONS(76),
    [anon_sym_box_set] = ACTIONS(76),
    [anon_sym_add] = ACTIONS(76),
    [anon_sym_sub] = ACTIONS(76),
    [anon_sym_mul] = ACTIONS(76),
    [anon_sym_cmpeq] = ACTIONS(76),
    [anon_sym_cmpne] = ACTIONS(76),
    [anon_sym_cmplt] = ACTIONS(76),
    [anon_sym_cmple] = ACTIONS(76),
    [anon_sym_cmpgt] = ACTIONS(76),
    [anon_sym_cmpge] = ACTIONS(76),
    [anon_sym_cons] = ACTIONS(76),
    [anon_sym_li] = ACTIONS(76),
    [anon_sym_jz] = ACTIONS(76),
    [anon_sym_jmp] = ACTIONS(76),
    [anon_sym_call] = ACTIONS(76),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [anon_sym_result] = ACTIONS(80),
    [anon_sym_ret] = ACTIONS(80),
    [anon_sym_halt] = ACTIONS(80),
    [anon_sym_nil] = ACTIONS(80),
    [anon_sym_mov] = ACTIONS(80),
    [anon_sym_head] = ACTIONS(80),
    [anon_sym_tail] = ACTIONS(80),
    [anon_sym_isempty] = ACTIONS(80),
    [anon_sym_box] = ACTIONS(80),
    [anon_sym_box_get] = ACTIONS(80),
    [anon_sym_box_set] = ACTIONS(80),
    [anon_sym_add] = ACTIONS(80),
    [anon_sym_sub] = ACTIONS(80),
    [anon_sym_mul] = ACTIONS(80),
    [anon_sym_cmpeq] = ACTIONS(80),
    [anon_sym_cmpne] = ACTIONS(80),
    [anon_sym_cmplt] = ACTIONS(80),
    [anon_sym_cmple] = ACTIONS(80),
    [anon_sym_cmpgt] = ACTIONS(80),
    [anon_sym_cmpge] = ACTIONS(80),
    [anon_sym_cons] = ACTIONS(80),
    [anon_sym_li] = ACTIONS(80),
    [anon_sym_jz] = ACTIONS(80),
    [anon_sym_jmp] = ACTIONS(80),
    [anon_sym_call] = ACTIONS(80),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(82),
    [sym_identifier] = ACTIONS(84),
    [anon_sym_result] = ACTIONS(84),
    [anon_sym_ret] = ACTIONS(84),
    [anon_sym_halt] = ACTIONS(84),
    [anon_sym_nil] = ACTIONS(84),
    [anon_sym_mov] = ACTIONS(84),
    [anon_sym_head] = ACTIONS(84),
    [anon_sym_tail] = ACTIONS(84),
    [anon_sym_isempty] = ACTIONS(84),
    [anon_sym_box] = ACTIONS(84),
    [anon_sym_box_get] = ACTIONS(84),
    [anon_sym_box_set] = ACTIONS(84),
    [anon_sym_add] = ACTIONS(84),
    [anon_sym_sub] = ACTIONS(84),
    [anon_sym_mul] = ACTIONS(84),
    [anon_sym_cmpeq] = ACTIONS(84),
    [anon_sym_cmpne] = ACTIONS(84),
    [anon_sym_cmplt] = ACTIONS(84),
    [anon_sym_cmple] = ACTIONS(84),
    [anon_sym_cmpgt] = ACTIONS(84),
    [anon_sym_cmpge] = ACTIONS(84),
    [anon_sym_cons] = ACTIONS(84),
    [anon_sym_li] = ACTIONS(84),
    [anon_sym_jz] = ACTIONS(84),
    [anon_sym_jmp] = ACTIONS(84),
    [anon_sym_call] = ACTIONS(84),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(86),
    [sym_identifier] = ACTIONS(88),
    [anon_sym_result] = ACTIONS(88),
    [anon_sym_ret] = ACTIONS(88),
    [anon_sym_halt] = ACTIONS(88),
    [anon_sym_nil] = ACTIONS(88),
    [anon_sym_mov] = ACTIONS(88),
    [anon_sym_head] = ACTIONS(88),
    [anon_sym_tail] = ACTIONS(88),
    [anon_sym_isempty] = ACTIONS(88),
    [anon_sym_box] = ACTIONS(88),
    [anon_sym_box_get] = ACTIONS(88),
    [anon_sym_box_set] = ACTIONS(88),
    [anon_sym_add] = ACTIONS(88),
    [anon_sym_sub] = ACTIONS(88),
    [anon_sym_mul] = ACTIONS(88),
    [anon_sym_cmpeq] = ACTIONS(88),
    [anon_sym_cmpne] = ACTIONS(88),
    [anon_sym_cmplt] = ACTIONS(88),
    [anon_sym_cmple] = ACTIONS(88),
    [anon_sym_cmpgt] = ACTIONS(88),
    [anon_sym_cmpge] = ACTIONS(88),
    [anon_sym_cons] = ACTIONS(88),
    [anon_sym_li] = ACTIONS(88),
    [anon_sym_jz] = ACTIONS(88),
    [anon_sym_jmp] = ACTIONS(88),
    [anon_sym_call] = ACTIONS(88),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(90),
    [sym_identifier] = ACTIONS(92),
    [anon_sym_result] = ACTIONS(92),
    [anon_sym_ret] = ACTIONS(92),
    [anon_sym_halt] = ACTIONS(92),
    [anon_sym_nil] = ACTIONS(92),
    [anon_sym_mov] = ACTIONS(92),
    [anon_sym_head] = ACTIONS(92),
    [anon_sym_tail] = ACTIONS(92),
    [anon_sym_isempty] = ACTIONS(92),
    [anon_sym_box] = ACTIONS(92),
    [anon_sym_box_get] = ACTIONS(92),
    [anon_sym_box_set] = ACTIONS(92),
    [anon_sym_add] = ACTIONS(92),
    [anon_sym_sub] = ACTIONS(92),
    [anon_sym_mul] = ACTIONS(92),
    [anon_sym_cmpeq] = ACTIONS(92),
    [anon_sym_cmpne] = ACTIONS(92),
    [anon_sym_cmplt] = ACTIONS(92),
    [anon_sym_cmple] = ACTIONS(92),
    [anon_sym_cmpgt] = ACTIONS(92),
    [anon_sym_cmpge] = ACTIONS(92),
    [anon_sym_cons] = ACTIONS(92),
    [anon_sym_li] = ACTIONS(92),
    [anon_sym_jz] = ACTIONS(92),
    [anon_sym_jmp] = ACTIONS(92),
    [anon_sym_call] = ACTIONS(92),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_COLON,
    ACTIONS(94), 1,
      sym_register,
  [10] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_COLON,
    ACTIONS(96), 1,
      sym_register,
  [20] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_COLON,
    ACTIONS(98), 1,
      sym_register,
  [30] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_COLON,
    ACTIONS(100), 1,
      sym_register,
  [40] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_COLON,
    ACTIONS(102), 1,
      sym_identifier,
  [50] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_COLON,
    ACTIONS(104), 1,
      sym_identifier,
  [60] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_COLON,
    ACTIONS(106), 1,
      sym_register,
  [70] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
  [77] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_COLON,
  [84] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_COMMA,
  [91] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_COMMA,
  [98] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      sym_register,
  [105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym_register,
  [112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      sym_immediate,
  [119] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_identifier,
  [126] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_COMMA,
  [133] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_COMMA,
  [140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_COMMA,
  [147] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_register,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 10,
  [SMALL_STATE(15)] = 20,
  [SMALL_STATE(16)] = 30,
  [SMALL_STATE(17)] = 40,
  [SMALL_STATE(18)] = 50,
  [SMALL_STATE(19)] = 60,
  [SMALL_STATE(20)] = 70,
  [SMALL_STATE(21)] = 77,
  [SMALL_STATE(22)] = 84,
  [SMALL_STATE(23)] = 91,
  [SMALL_STATE(24)] = 98,
  [SMALL_STATE(25)] = 105,
  [SMALL_STATE(26)] = 112,
  [SMALL_STATE(27)] = 119,
  [SMALL_STATE(28)] = 126,
  [SMALL_STATE(29)] = 133,
  [SMALL_STATE(30)] = 140,
  [SMALL_STATE(31)] = 147,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nullary_instruction, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nullary_instruction, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__label_name, 1, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_result, 2, 0, 2),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_result, 2, 0, 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reg_instruction, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reg_instruction, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reg_reg_instruction, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reg_reg_instruction, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_instruction, 2, 0, 3),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_instruction, 2, 0, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 4),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 2, 0, 4),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imm_instruction, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_imm_instruction, 4, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch_instruction, 4, 0, 5),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch_instruction, 4, 0, 5),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reg_reg_reg_instruction, 6, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reg_reg_reg_instruction, 6, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [108] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_redextape_asm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "redextape_asm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
