[package]
name = "redextape-native"
version = "0.0.0"
edition = "2024"
license = "GPL-3.0-only"

[features]
default = ["cranelift"]
cranelift = ["dep:cranelift-jit", "dep:cranelift-module", "dep:cranelift-frontend", "dep:cranelift-codegen", "dep:cranelift-object", "dep:cranelift-native"]
llvm = ["dep:inkwell"]

[dependencies]
redextape-core = { path = "../redextape-core" }
redextape-native-rt = { path = "../redextape-native-rt" }
cranelift-jit = { version = "0.134", optional = true }
cranelift-module = { version = "0.134", optional = true }
cranelift-frontend = { version = "0.134", optional = true }
cranelift-codegen = { version = "0.134", optional = true }
cranelift-object = { version = "0.134", optional = true }
cranelift-native = { version = "0.134", optional = true }
inkwell = { version = "0.9", optional = true, features = ["llvm22-1"] }

[dev-dependencies]
proptest = "1"
redextape-test-support = { path = "../redextape-test-support" }

[lints]
workspace = true
